"""Render an :mod:`.ir` IRTranslationUnit as C++ source text.

The emitter is purely string-building: it never inspects the original
AST.  It walks the IR top-down, prints subprograms in order, and
preserves comments attached by ``annotate``.

Aim is *readable* C++ — see R8 in the README.  We default to plain
standard-library spellings and only reach into ``fortran::io`` /
``fortran::FortranString`` when the rules say we must.
"""

from __future__ import annotations

from io import StringIO
from typing import Iterable

from flang_ast import Comment

from .ir import (
    IRAssignment,
    IRBinaryOp,
    IRCall,
    IRComment,
    IRDo,
    IRExpr,
    IRFunctionCall,
    IRIf,
    IRLiteral,
    IRLocal,
    IRName,
    IRPrint,
    IRRaw,
    IRReturn,
    IRStatement,
    IRSubprogram,
    IRTranslationUnit,
    IRType,
    IRUnaryOp,
    IRUnsupported,
)


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------


def emit_translation_unit(tu: IRTranslationUnit) -> str:
    """Render the whole translation unit to a single C++ source string."""
    out = StringIO()
    _emit_file_header(out, tu)
    _emit_includes(out, tu)
    for sub in tu.subprograms:
        out.write("\n")
        _emit_subprogram(out, sub)
    _emit_cpp_main(out, tu)
    return out.getvalue()


# ---------------------------------------------------------------------------
# File-level scaffolding
# ---------------------------------------------------------------------------


def _emit_file_header(out: StringIO, tu: IRTranslationUnit) -> None:
    out.write("// Generated by fortran-to-cpp.\n")
    if tu.source_file:
        out.write(f"// Source: {tu.source_file}\n")
    out.write("//\n")
    out.write("// This file follows the rules in flang/tools/fortran-to-cpp/README.md.\n")
    out.write("// Edit the original Fortran source rather than the generated C++.\n\n")


def _emit_includes(out: StringIO, tu: IRTranslationUnit) -> None:
    includes = {"<cstdint>", "<format>", "<iostream>", "<string_view>",
                '"fortran/runtime.hpp"'}
    for inc in sorted(includes):
        out.write(f"#include {inc}\n")
    out.write("\nusing namespace std::string_view_literals;\n")


def _emit_cpp_main(out: StringIO, tu: IRTranslationUnit) -> None:
    """If a MainProgram exists, generate a C++ ``main`` that calls it.

    Subprograms-only translation units don't need a main.
    """
    main_progs = [s for s in tu.subprograms if s.kind == "main"]
    if not main_progs:
        return
    main = main_progs[0]
    out.write("\nint main() {\n")
    out.write(f"  {main.name}();\n")
    out.write("  return 0;\n")
    out.write("}\n")


# ---------------------------------------------------------------------------
# Subprograms
# ---------------------------------------------------------------------------


def _emit_subprogram(out: StringIO, sub: IRSubprogram) -> None:
    _emit_comment_block(out, sub.leading_comments, indent=0)
    # Signature
    if sub.kind == "main":
        out.write(f"void {sub.name}(")
    elif sub.kind == "function":
        ret = sub.return_type.cpp if sub.return_type else "void"
        out.write(f"{ret} {sub.name}(")
    else:  # subroutine
        out.write(f"void {sub.name}(")
    out.write(", ".join(p.cpp_param_decl() for p in sub.parameters))
    out.write(") {\n")

    # Local variable declarations.
    for loc in sub.locals:
        _emit_local(out, loc, indent=1)
    if sub.locals and sub.body:
        out.write("\n")

    # Body.
    for stmt in sub.body:
        _emit_statement(out, stmt, indent=1)

    # For a function with no explicit return: emit one based on the
    # local variable that shared the function name (which lowering
    # already deleted and stored on ``return_type``).  Generated
    # function bodies assign to a synthesized variable also named
    # after the function; we emit a ``return`` of that at the end.
    if sub.kind == "function" and sub.return_type is not None:
        if not _ends_with_return(sub.body):
            out.write(f"  return {sub.name}_result;\n")

    out.write("}\n")


def _emit_local(out: StringIO, loc: IRLocal, *, indent: int) -> None:
    pad = "  " * indent
    prefix = "constexpr " if loc.is_parameter else ""
    out.write(f"{pad}{prefix}{loc.type.cpp} {loc.name}")
    if loc.initializer is not None:
        out.write(f" = {_render_expr(loc.initializer)}")
    elif loc.type.is_integer or loc.type.is_real:
        # Match Fortran's IMPLICIT-typed locals (zero-initialized
        # under most compilers when -finit-{integer,real} is set).
        out.write("{}")
    out.write(";\n")


def _ends_with_return(body: list[IRStatement]) -> bool:
    return bool(body) and isinstance(body[-1], IRReturn)


# ---------------------------------------------------------------------------
# Statements
# ---------------------------------------------------------------------------


def _emit_statement(out: StringIO, stmt: IRStatement, *, indent: int) -> None:
    pad = "  " * indent
    if isinstance(stmt, IRComment):
        _emit_comment_block(out, stmt.comments, indent=indent)
        return
    if isinstance(stmt, IRAssignment):
        _emit_comment_block(out, stmt.leading_comments, indent=indent)
        out.write(f"{pad}{_render_expr(stmt.target)} = {_render_expr(stmt.value)};")
        _emit_trailing(out, stmt.trailing_comments)
        return
    if isinstance(stmt, IRCall):
        _emit_comment_block(out, stmt.leading_comments, indent=indent)
        out.write(f"{pad}{stmt.callee}(")
        out.write(", ".join(_render_expr(a) for a in stmt.args))
        out.write(");")
        _emit_trailing(out, stmt.trailing_comments)
        return
    if isinstance(stmt, IRPrint):
        _emit_comment_block(out, stmt.leading_comments, indent=indent)
        out.write(f"{pad}{stmt.stream}")
        # Fortran list-directed I/O typically separates with a space.
        sep_chunks = []
        for i, item in enumerate(stmt.items):
            if i > 0:
                sep_chunks.append(" << ' '")
            sep_chunks.append(f" << {_render_expr(item)}")
        out.write("".join(sep_chunks))
        out.write(" << '\\n';")
        _emit_trailing(out, stmt.trailing_comments)
        return
    if isinstance(stmt, IRReturn):
        _emit_comment_block(out, stmt.leading_comments, indent=indent)
        if stmt.value is None:
            out.write(f"{pad}return;")
        else:
            out.write(f"{pad}return {_render_expr(stmt.value)};")
        _emit_trailing(out, stmt.trailing_comments)
        return
    if isinstance(stmt, IRIf):
        _emit_if(out, stmt, indent=indent)
        return
    if isinstance(stmt, IRDo):
        _emit_do(out, stmt, indent=indent)
        return
    if isinstance(stmt, IRUnsupported):
        _emit_unsupported(out, stmt, indent=indent)
        return
    out.write(f"{pad}// TODO: unhandled IR statement {type(stmt).__name__}\n")


def _emit_if(out: StringIO, node: IRIf, *, indent: int) -> None:
    pad = "  " * indent
    _emit_comment_block(out, node.leading_comments, indent=indent)
    for i, (cond, body) in enumerate(node.branches):
        keyword = "if" if i == 0 else "else if"
        out.write(f"{pad}{keyword} ({_render_expr(cond)}) {{\n")
        for s in body:
            _emit_statement(out, s, indent=indent + 1)
        out.write(f"{pad}}}")
        if i + 1 < len(node.branches) or node.else_body is not None:
            out.write(" ")
        else:
            out.write("\n")
    if node.else_body is not None:
        out.write("else {\n")
        for s in node.else_body:
            _emit_statement(out, s, indent=indent + 1)
        out.write(f"{pad}}}\n")
    _emit_trailing(out, node.trailing_comments)


def _emit_do(out: StringIO, node: IRDo, *, indent: int) -> None:
    pad = "  " * indent
    _emit_comment_block(out, node.leading_comments, indent=indent)
    var = node.var
    lo = _render_expr(node.lower)
    hi = _render_expr(node.upper)
    step = _render_expr(node.step) if node.step is not None else "1"
    # For the common step==1 case, write a clean ``i <= hi`` form.
    if step == "1":
        out.write(
            f"{pad}for ({var} = {lo}; {var} <= {hi}; ++{var}) {{\n"
        )
    else:
        out.write(
            f"{pad}for ({var} = {lo}; "
            f"({step} >= 0 ? {var} <= {hi} : {var} >= {hi}); "
            f"{var} += {step}) {{\n"
        )
    for s in node.body:
        _emit_statement(out, s, indent=indent + 1)
    out.write(f"{pad}}}\n")
    _emit_trailing(out, node.trailing_comments)


def _emit_unsupported(
    out: StringIO, stmt: IRUnsupported, *, indent: int
) -> None:
    pad = "  " * indent
    _emit_comment_block(out, stmt.leading_comments, indent=indent)
    out.write(f"{pad}// TODO: fortran-to-cpp does not yet translate "
              f"{stmt.kind}\n")
    if stmt.note:
        out.write(f"{pad}//       {stmt.note}\n")
    for line in stmt.source_text.splitlines() or [stmt.source_text]:
        out.write(f"{pad}//   {line.rstrip()}\n")


# ---------------------------------------------------------------------------
# Expressions
# ---------------------------------------------------------------------------


def _render_expr(expr: IRExpr) -> str:
    if isinstance(expr, IRLiteral):
        return expr.cpp_text
    if isinstance(expr, IRName):
        return expr.name
    if isinstance(expr, IRBinaryOp):
        return f"{_render_expr(expr.lhs)} {expr.op} {_render_expr(expr.rhs)}"
    if isinstance(expr, IRUnaryOp):
        if expr.op == "()":
            return f"({_render_expr(expr.operand)})"
        return f"{expr.op}{_render_expr(expr.operand)}"
    if isinstance(expr, IRFunctionCall):
        args = ", ".join(_render_expr(a) for a in expr.args)
        return f"{expr.callee}({args})"
    if isinstance(expr, IRRaw):
        return expr.text
    return f"/* unhandled expr {type(expr).__name__} */"


# ---------------------------------------------------------------------------
# Comment rendering
# ---------------------------------------------------------------------------


def _emit_comment_block(
    out: StringIO, comments: Iterable[Comment], *, indent: int
) -> None:
    pad = "  " * indent
    for c in comments:
        # Strip the leading "!" and any single leading blank that flang
        # left in place, so "// hello" looks like real C++ comments.
        body = c.text
        if body.startswith(" "):
            body = body[1:]
        out.write(f"{pad}// {body.rstrip()}\n")


def _emit_trailing(out: StringIO, comments: Iterable[Comment]) -> None:
    comments = list(comments)
    if not comments:
        out.write("\n")
        return
    first = comments[0]
    body = first.text.lstrip("!").lstrip()
    out.write(f"  // {body.rstrip()}\n")
    for c in comments[1:]:
        out.write(f"  // {c.text.lstrip('!').lstrip().rstrip()}\n")
