"""Render an :mod:`.ir` IRTranslationUnit as C++ source text.

The emitter is purely string-building: it never inspects the original
AST.  It walks the IR top-down, prints subprograms in order, and
preserves comments attached by ``annotate``.

Aim is *readable* C++ — see R8 in the README.  We default to plain
standard-library spellings and only reach into ``fortran::io`` /
``fortran::FortranString`` when the rules say we must.
"""

from __future__ import annotations

from io import StringIO
from typing import Iterable

from flang_ast import Comment

from .errors import ConversionError
from .ir import (
    IRAllocate,
    IRArrayConstructor,
    IRLambda,
    IRAssignment,
    IRBinaryOp,
    IRBlock,
    IRCall,
    IRCast,
    IRCaseClause,
    IRComment,
    IRCycle,
    IRDeallocate,
    IRDo,
    IRExit,
    IRExpr,
    IRFunctionCall,
    IRIf,
    IRImpliedDo,
    IRLiteral,
    IRLocal,
    IRMember,
    IRName,
    IRSubstr,
    IRPointerAssign,
    IRPrint,
    IRRaw,
    IRDirectRead,
    IRDirectWrite,
    IRUnformattedDirectRead,
    IRUnformattedDirectWrite,
    IRInquire,
    IRFilePosition,
    IRRead,
    IRReturn,
    IRSection,
    IRSelectCase,
    IRStateStruct,
    IRStatement,
    IRStop,
    IRSubprogram,
    IRTranslationUnit,
    IRTriplet,
    IRType,
    IRUnaryOp,
    IRUnsupported,
    IRWhile,
)


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------


def emit_translation_unit(
    tu: IRTranslationUnit, *, shared_header: str | None = None
) -> str:
    """Render the whole translation unit to a single C++ source string.

    When ``shared_header`` is given (multi-file projects), the shared
    structs — derived types, module state, common blocks — are assumed to
    live in that header (see :func:`emit_shared_header`); this file just
    ``#include``\\s it instead of re-defining them.
    """
    out = StringIO()
    _emit_file_header(out, tu)
    _emit_includes(out, tu, shared_header=shared_header)
    if shared_header is None:
        # Single-file: all structs, constants and prototypes live here.
        _emit_module_constants(out, tu)
        _emit_derived_types(out, tu)
        _emit_module_structs(out, tu)
        _emit_common_structs(out, tu)
        _emit_local_state_structs(out, tu)
        _emit_prototypes(out, tu)
    # With a shared header the structs and prototypes are declared there;
    # this file only carries the routine definitions.  A procedure-taking
    # routine is a template, though, and a template's definition must be
    # visible at every call site — so those live in the shared header
    # (emit_shared_header), not here.  In single-file mode (no shared
    # header) everything is one TU, so templates are defined here as usual.
    for sub in tu.subprograms:
        if shared_header is not None and _is_template_sub(sub):
            continue
        out.write("\n")
        _emit_subprogram(out, sub)
    _emit_cpp_main(out, tu)
    return out.getvalue()


def emit_shared_header(tu: IRTranslationUnit, *, guard: str) -> str:
    """Render everything a multi-file project's files share: derived
    types, module / common / per-routine state structs, and every
    subprogram prototype.  Included by every generated ``.cpp`` so
    cross-file references and calls resolve to one set of definitions."""
    out = StringIO()
    out.write("// Generated by fortran-to-cpp (shared module/type header).\n")
    out.write("// Edit the original Fortran source rather than this file.\n\n")
    out.write(f"#ifndef {guard}\n#define {guard}\n\n")
    out.write("#include <functional>\n")
    out.write('#include "fortran/runtime.hpp"\n')
    out.write("\nusing namespace std::string_view_literals;\n")
    # Constants first — array bounds in the structs below may use them.
    _emit_module_constants(out, tu)
    _emit_derived_types(out, tu)
    _emit_module_structs(out, tu)
    _emit_common_structs(out, tu)
    _emit_local_state_structs(out, tu)
    _emit_prototypes(out, tu)
    # Procedure-taking routines are function templates: their definitions
    # must be visible wherever they're called, so they live here in the
    # shared header (the per-file ``.cpp`` skips them).  Prototypes above
    # already forward-declare them, so a template that calls another
    # template resolves regardless of definition order.
    seen: set[str] = set()
    for sub in tu.subprograms:
        if not _is_template_sub(sub) or sub.name in seen:
            continue
        seen.add(sub.name)
        out.write("\n")
        _emit_subprogram(out, sub)
    out.write(f"\n#endif  // {guard}\n")
    return out.getvalue()


def _emit_derived_types(out: StringIO, tu: IRTranslationUnit) -> None:
    if not tu.derived_types:
        return
    out.write("\n// ---- User-defined types ----\n")
    for dt in tu.derived_types:
        out.write(f"\nstruct {dt.cpp_type} {{\n")
        for field_local in dt.fields:
            _emit_local(out, field_local, indent=1, storage="struct")
        out.write("};\n")


def _emit_module_constants(out: StringIO, tu: IRTranslationUnit) -> None:
    """Module ``PARAMETER``\\s are compile-time constants — emit them as
    file/header-scope ``inline constexpr`` so they can be referenced
    without a module instance (in routine bodies, array bounds, and even
    workspace/derived-type struct fields)."""
    params = [(m, v) for m in tu.modules for v in m.variables if v.is_parameter]
    if not params:
        return
    out.write("\n// ---- Module parameters (compile-time constants) ----\n")
    for _, var in params:
        _emit_local(out, var, indent=0, storage="namespace")


def _emit_module_structs(out: StringIO, tu: IRTranslationUnit) -> None:
    # Only mutable module variables become struct members; PARAMETERs are
    # emitted as free constants by ``_emit_module_constants``.
    modules = [
        m for m in tu.modules if any(not v.is_parameter for v in m.variables)
    ]
    if not modules:
        return
    out.write("\n// ---- Module state structs (module variables) ----\n")
    for m in modules:
        out.write(f"\nstruct {m.cpp_type} {{\n")
        for var in m.variables:
            if not var.is_parameter:
                _emit_local(out, var, indent=1, storage="struct")
        out.write("};\n")


def _emit_common_structs(out: StringIO, tu: IRTranslationUnit) -> None:
    if tu.common_structs:
        out.write("\n// ---- Common block structs (shared program state) ----\n")
        for s in tu.common_structs:
            _emit_one_struct(out, s)


def _emit_local_state_structs(out: StringIO, tu: IRTranslationUnit) -> None:
    """Per-subprogram state (SAVE locals, workspaces) — these belong with
    the routine's definition, so they stay in the routine's own file.

    Deduplicated by struct name: a utility routine duplicated across
    several files (common in old code) yields several subprograms with
    the same workspace/save struct, which must be defined only once."""
    seen: set[str] = set()

    def emit_unique(structs: list[IRStateStruct]) -> None:
        for s in structs:
            if s.cpp_type not in seen:
                seen.add(s.cpp_type)
                _emit_one_struct(out, s)

    save_structs = [
        s.save_struct for s in tu.subprograms if s.save_struct is not None
    ]
    if save_structs:
        out.write("\n// ---- Per-subprogram state structs (SAVE locals) ----\n")
        emit_unique(save_structs)
    workspaces = [s.workspace for s in tu.subprograms if s.workspace is not None]
    if workspaces:
        out.write(
            "\n// ---- Per-subprogram workspaces (hoisted local arrays, "
            "allocated once) ----\n"
        )
        emit_unique(workspaces)


def _emit_one_struct(out: StringIO, s: IRStateStruct) -> None:
    out.write(f"\nstruct {s.cpp_type} {{\n")
    for field_local in s.fields:
        # Reuse the local-declaration emitter so types and defaults
        # stay consistent.
        _emit_local(out, field_local, indent=1, storage="struct")
    out.write("};\n")


# ---------------------------------------------------------------------------
# File-level scaffolding
# ---------------------------------------------------------------------------


def _emit_file_header(out: StringIO, tu: IRTranslationUnit) -> None:
    out.write("// Generated by fortran-to-cpp.\n")
    if tu.source_file:
        out.write(f"// Source: {tu.source_file}\n")
    out.write("//\n")
    out.write("// This file follows the rules in flang/tools/fortran-to-cpp/README.md.\n")
    out.write("// Edit the original Fortran source rather than the generated C++.\n\n")


def _emit_includes(
    out: StringIO, tu: IRTranslationUnit, *, shared_header: str | None = None
) -> None:
    # For now we include the kitchen sink (cmath for intrinsics, format
    # for inline std::format calls).  Once the IR carries enough info
    # we can prune this on a per-translation-unit basis.
    includes = {"<algorithm>", "<cmath>", "<cstdint>", "<cstdlib>",
                "<format>", "<functional>", "<iostream>", "<limits>",
                "<optional>", "<sstream>", "<string_view>",
                '"fortran/runtime.hpp"'}
    if shared_header is not None:
        # The shared header already pulls in runtime.hpp.
        includes.discard('"fortran/runtime.hpp"')
        includes.add(f'"{shared_header}"')
    for inc in sorted(includes):
        out.write(f"#include {inc}\n")
    out.write("\nusing namespace std::string_view_literals;\n")


def _emit_cpp_main(out: StringIO, tu: IRTranslationUnit) -> None:
    """If a MainProgram exists, generate a C++ ``main`` that calls it.

    Subprograms-only translation units don't need a main.
    """
    main_progs = [s for s in tu.subprograms if s.kind == "main"]
    if not main_progs:
        return
    main = main_progs[0]
    out.write("\nint main(int argc, char** argv) {\n")
    out.write("  fortran::set_command_args(argc, argv);\n")
    out.write(f"  {main.name}();\n")
    out.write("  return 0;\n")
    out.write("}\n")


# ---------------------------------------------------------------------------
# Subprograms
# ---------------------------------------------------------------------------


def _proc_param_indices(sub: IRSubprogram) -> list[int]:
    """Positions of ``sub``'s dummy-procedure parameters."""
    return [i for i, p in enumerate(sub.parameters) if p.type.is_procedure]


def _is_template_sub(sub: IRSubprogram) -> bool:
    """A routine that takes a dummy procedure is emitted as a function
    template: each procedure parameter becomes a deduced type ``F<k>``
    rather than a fixed ``std::function``.  This sidesteps cross-program
    signature inference entirely — the compiler deduces the callback type
    from whatever is actually passed, and a forwarded callback keeps its
    (already deduced) type down the chain.  (Procedure *actuals* are wrapped
    in a generic lambda at the call site so even a higher-order routine
    passed as a callback is a concrete object the deduction can latch onto.)"""
    return sub.kind != "main" and bool(_proc_param_indices(sub))


def _template_prefix(sub: IRSubprogram) -> str:
    """``template <class F0, class F1, ...>`` for a procedure-taking
    routine, one type parameter per dummy procedure; ``""`` otherwise."""
    n = len(_proc_param_indices(sub))
    if not n:
        return ""
    return "template <" + ", ".join(f"class F{k}" for k in range(n)) + ">\n"


def _signature(sub: IRSubprogram, *, with_defaults: bool = True) -> str:
    if sub.kind == "function" and sub.return_type is not None:
        ret = sub.return_type.cpp
    else:
        ret = "void"
    # State parameters first (D2.b — granular per-routine state), then the
    # user-visible Fortran dummy args.  Default arguments live on the
    # prototype only (a C++ default may be specified once) and only on the
    # trailing run of OPTIONAL params — C++ forbids a defaulted parameter
    # before a non-defaulted one (Fortran allows optionals anywhere).
    parts = [f"{sp.struct_type}& {sp.name}" for sp in sub.state_params]
    params = sub.parameters
    default_from = len(params)
    for i in range(len(params) - 1, -1, -1):
        if params[i].optional:  # optional scalar (=nullopt) or array (={})
            default_from = i
        else:
            break
    # A procedure-taking routine is a template; render each dummy procedure
    # as its deduced type ``const F<k>&`` instead of a concrete std::function.
    proc_pos = {idx: k for k, idx in enumerate(_proc_param_indices(sub))}
    for i, p in enumerate(params):
        if i in proc_pos:
            parts.append(f"const F{proc_pos[i]}& {p.name}")
        else:
            parts.append(
                p.cpp_param_decl(with_default=with_defaults and i >= default_from)
            )
    return f"{ret} {sub.name}({', '.join(parts)})"



def _emit_prototypes(out: StringIO, tu: IRTranslationUnit) -> None:
    """Forward-declare every subprogram so definitions can appear in any
    order (and mutually recursive routines work)."""
    subs = [s for s in tu.subprograms if s.kind != "main"]
    if not subs:
        return
    out.write("\n// ---- Forward declarations ----\n")
    seen: set[str] = set()  # a routine duplicated across files: declare once
    for sub in subs:
        if sub.name in seen:
            continue
        seen.add(sub.name)
        out.write(f"{_template_prefix(sub)}{_signature(sub)};\n")


def _emit_equiv_group(out: StringIO, g, idx: int) -> None:
    """Render one EQUIVALENCE class as a local struct + bindings.

    Layout (the SPICE pattern -- all members share offset 0):
        struct <CppType> {
          alignas(<A>) std::byte _store[<N>]{};
          fortran::EquivSlot<T,0>  scalar { _store };
          fortran::EquivArray<T,N,0> arr  { _store };
          fortran::FortranString<L> chr;      // character member (special-cased)
        } _eqK;
        auto& <name> = _eqK.<name>;
    The CHARACTER alias is emitted as a plain ``FortranString<L>`` --
    the shared bytes form a single character record, and Fortran code
    addresses it as a substring.
    """
    pad = "  "
    out.write(f"{pad}struct {g.cpp_type} {{\n")
    out.write(f"{pad}  alignas({g.alignment}) std::byte _store[{g.byte_size}]{{}};\n")
    for m in g.members:
        if m.is_character:
            out.write(
                f"{pad}  fortran::FortranString<{m.count}> {m.name};\n"
            )
        elif m.count is None:
            out.write(
                f"{pad}  fortran::EquivSlot<{m.cpp_elem_type}, 0> "
                f"{m.name}{{_store}};\n"
            )
        else:
            out.write(
                f"{pad}  fortran::EquivArray<{m.cpp_elem_type}, "
                f"{m.count}, 0> {m.name}{{_store}};\n"
            )
    out.write(f"{pad}}} _eq{idx};\n")
    for m in g.members:
        out.write(f"{pad}auto& {m.name} = _eq{idx}.{m.name};\n")


def _emit_subprogram(out: StringIO, sub: IRSubprogram) -> None:
    _emit_comment_block(out, sub.leading_comments, indent=0)
    # The prototype carries default arguments; the definition omits them.
    out.write(_template_prefix(sub))
    out.write(_signature(sub, with_defaults=False))
    out.write(" {\n")

    # Emission order: state-*instance* locals (the ``Mod mod{}`` objects
    # the bindings refer to) first, then the bindings, then ordinary
    # locals.  This lets an ordinary local that captures a bound name —
    # notably a statement-function lambda using a COMMON/module variable
    # (``auto f = [&]{ ... re ... }`` with ``auto& re = parmb.re``) — see
    # the binding, which would otherwise be declared after it.
    def _is_state_instance(loc: IRLocal) -> bool:
        return isinstance(loc.initializer, IRRaw) and loc.initializer.text == "{}"

    instance_locals = [loc for loc in sub.locals if _is_state_instance(loc)]
    other_locals = [loc for loc in sub.locals if not _is_state_instance(loc)]
    for loc in instance_locals:
        _emit_local(out, loc, indent=1)

    # EQUIVALENCE classes: one struct per group holding the shared byte
    # buffer plus a typed proxy per aliased Fortran name, then a binding
    # so the body refers to each name unqualified.
    for idx, g in enumerate(sub.equiv_groups):
        _emit_equiv_group(out, g, idx)

    # State bindings: ``auto& field = param.field;`` so the body can use
    # plumbed common / save / module / workspace state by its original
    # name and stay clean.  Param-bindings must come early (before
    # ordinary locals, in case a local's initializer captures one);
    # local-to-local aliases (an empty ``param``, the same-type
    # EQUIVALENCE renaming) must come *after* the canonical local has
    # been declared, so emit those last.
    param_bindings = [b for b in sub.state_bindings if b.param]
    alias_bindings = [b for b in sub.state_bindings if not b.param]
    for b in param_bindings:
        if b.view is not None:
            # Reshaped view of a shared COMMON field (storage association).
            # Two flavours:
            #   * ArrayRef<...>(field.data() + N, ...) -- an array sub-view;
            #     ArrayRef has value semantics (cheap pointer + bounds), so
            #     bind by value.
            #   * field(N) -- a scalar reference to one canonical element
            #     (the routine declares it as a scalar at a fixed byte
            #     offset inside an array canonical, e.g. ``ST0`` at C1(1)).
            #     Bind by reference so writes through the canonical (e.g.
            #     RECALC updating C1) are visible to this routine's name.
            if b.view.lstrip().startswith("fortran::ArrayRef<"):
                out.write(f"  auto {b.name} = {b.view};\n")
            else:
                out.write(f"  auto& {b.name} = {b.view};\n")
        else:
            out.write(f"  auto& {b.name} = {b.param}.{b.field};\n")

    for loc in other_locals:
        _emit_local(out, loc, indent=1)

    for b in alias_bindings:
        out.write(f"  auto& {b.name} = {b.field};\n")

    if (sub.locals or sub.state_bindings) and sub.body:
        out.write("\n")

    # Body.
    for stmt in sub.body:
        _emit_statement(out, stmt, indent=1)

    # For a function with no explicit return: emit one based on the
    # local variable that shared the function name (which lowering
    # has already renamed to ``<name>_result``).
    if sub.kind == "function" and sub.return_type is not None:
        if not _ends_with_return(sub.body):
            if sub.body:
                out.write("\n")
            out.write(f"  return {sub.name}_result;\n")

    out.write("}\n")


def _is_scalar_constant(expr: object) -> bool:
    """True for a scalar constant expression — a literal or a unary
    op (e.g. negation) over one.  Used to recognize a whole-array scalar
    initializer (``= -9999.0``) versus an array-valued initializer (an
    array constructor or an elementwise expression)."""
    if isinstance(expr, IRLiteral):
        return True
    if isinstance(expr, IRUnaryOp):
        return _is_scalar_constant(expr.operand)
    return False


def _try_static_lower_literals(
    lower_exprs: tuple[str, ...],
) -> tuple[int, ...] | None:
    """Parse a tuple of per-dimension lower-bound expressions; return the
    integer values if every entry is a literal integer (optionally signed),
    else ``None``.  Used to decide whether a local owning array should be
    emitted as ``Array<T, R, std::array<index_t, R>{...}>`` (compile-time
    lower bounds: indexing math constant-folds the subtraction) rather than
    the runtime ``Array<T, R>`` form."""
    if not lower_exprs:
        return None
    values: list[int] = []
    for expr in lower_exprs:
        s = expr.strip()
        # Strip an outer (...) -- the converter sometimes wraps a signed
        # literal in parens via the operator-precedence layer.
        while s.startswith("(") and s.endswith(")"):
            inner = s[1:-1].strip()
            # Only strip when the outer parens are matched at the top level
            # (no early closing).  Easy check for our well-formed input.
            if inner.count("(") == inner.count(")"):
                s = inner
            else:
                break
        if s.startswith(("-", "+")):
            sign, body = s[0], s[1:].lstrip()
        else:
            sign, body = "+", s
        # Strip any trailing C++ literal suffix (uUlL).
        while body and body[-1] in "uUlL":
            body = body[:-1]
        if not body.isdigit():
            return None
        values.append(int(sign + body))
    return tuple(values)


def _static_lower_cpp_type(loc: "IRLocal") -> str | None:
    """Return the ``Array<T, R, std::array{...}>`` spelling for ``loc`` when
    every declared lower bound is a literal integer; ``None`` when the
    runtime form is required (no explicit bounds, or some bound is a
    non-literal expression).  Caller still uses the runtime form when this
    returns ``None``."""
    if not loc.type.is_array:
        return None
    lbs = _try_static_lower_literals(loc.type.array_lower_bound_exprs)
    if lbs is None:
        return None
    rank = loc.type.array_rank
    if len(lbs) != rank:
        return None
    # Render the C++ ``std::array<index_t, R>{lbs...}`` NTTP and substitute
    # it for the trailing ``>`` of the runtime spelling.  The runtime cpp is
    # ``fortran::Array<T, R>`` (or similar with namespace prefix).
    cpp = loc.type.cpp
    if not cpp.endswith(">"):
        return None
    inner = ",".join(str(v) for v in lbs)
    nttp = f"std::array<fortran::index_t, {rank}>{{{inner}}}"
    # Splice the NTTP in before the closing ``>``.
    return cpp[:-1] + f", {nttp}>"


def _emit_local(
    out: StringIO, loc: IRLocal, *, indent: int, storage: str = "local"
) -> None:
    pad = "  " * indent
    _emit_comment_block(out, loc.leading_comments, indent=indent)
    # PARAMETER constants: scalars of literal type can be ``constexpr``;
    # arrays (``fortran::Array`` — a non-literal type, often with a
    # runtime-evaluated initializer) must fall back to ``const``.  The
    # storage qualifier depends on where the declaration lives:
    #   * ``local``     — a function-body variable (no extra qualifier);
    #   * ``struct``    — a data member (``static`` / ``static inline``);
    #   * ``namespace`` — a file/header-scope constant (``inline`` so the
    #                     definition is shared across translation units).
    if loc.is_parameter:
        if loc.type.is_array:
            prefix = {
                "local": "const ",
                "struct": "static inline const ",
                "namespace": "inline const ",
            }[storage]
        else:
            prefix = {
                "local": "constexpr ",
                "struct": "static constexpr ",
                "namespace": "inline constexpr ",
            }[storage]
    else:
        prefix = ""
    # An assumed-length CHARACTER *array* local (an ENTRY-shared dummy of a
    # sibling entry, not this entry's argument) is a character-array view,
    # not an owning ``Array<std::string_view>`` — which isn't a real type.
    # Emit a null ``CharArrayRef`` so element/substring access type-checks;
    # the code that uses it is unreachable for this entry.
    if (
        loc.type.is_array
        and loc.type.element_type_cpp == "std::string_view"
        and loc.type.array_rank == 1
    ):
        out.write(f"{pad}{prefix}fortran::CharArrayRef {loc.name}{{}};")
        _emit_trailing(out, loc.trailing_comments)
        return
    if (
        loc.type.is_array
        and _is_scalar_constant(loc.initializer)
        and loc.type.array_extent_exprs
    ):
        # Whole-array scalar initializer (Fortran ``real :: a(n) = 0.0`` or
        # ``= -9999.0``): build the array with its shape and broadcast the
        # scalar constant expression to every element.  An array-valued
        # initializer (array constructor) keeps the plain ``= ...`` form
        # below.
        fill = _render_expr(loc.initializer)
        extents = ", ".join(loc.type.array_extent_exprs)
        # Prefer the compile-time-lower-bounds form when every declared
        # lower bound is an integer literal: the bound becomes part of the
        # type and ``a(i)``'s ``(i - lower)`` constant-folds.  This form
        # uses the ``Array<T, R, Lower>(extents, fill)`` ctor that the
        # runtime grew alongside the static ``Lower`` NTTP.  Otherwise fall
        # back to the runtime ``(lower, extents, fill)`` ctor; default the
        # lower bounds to 1 when none were declared.
        static_cpp = _static_lower_cpp_type(loc)
        if static_cpp is not None:
            out.write(
                f"{pad}{prefix}{static_cpp} {loc.name}"
                f"{{{{{extents}}}, {fill}}};"
            )
        else:
            if loc.type.array_lower_bound_exprs:
                lowers = ", ".join(loc.type.array_lower_bound_exprs)
            else:
                lowers = ", ".join(["1"] * len(loc.type.array_extent_exprs))
            out.write(
                f"{pad}{prefix}{loc.type.cpp} {loc.name}"
                f"{{{{{lowers}}}, {{{extents}}}, {fill}}};"
            )
        _emit_trailing(out, loc.trailing_comments)
        return
    if loc.type.is_array and loc.initializer is None:
        if not loc.type.array_extent_exprs:
            # Deferred-shape (allocatable) array: default-construct
            # empty; an ALLOCATE statement sizes it later.
            out.write(f"{pad}{prefix}{loc.type.cpp} {loc.name};")
            _emit_trailing(out, loc.trailing_comments)
            return
        # Brace-init form ``Array<T,R> name{ {extents} };`` (runtime lb
        # defaults to 1, runtime explicit lb uses ``{ {lowers}, {extents} }``,
        # or compile-time lb spells the bound in the type and uses
        # ``{ {extents} }``).  Braces rather than parens so the same emit
        # works whether ``name`` is a local variable or a struct data
        # member (parens aren't allowed for default member initializers).
        extents = ", ".join(loc.type.array_extent_exprs)
        static_cpp = _static_lower_cpp_type(loc)
        if static_cpp is not None:
            out.write(f"{pad}{prefix}{static_cpp} {loc.name}{{{{{extents}}}}};")
        elif loc.type.array_lower_bound_exprs:
            lowers = ", ".join(loc.type.array_lower_bound_exprs)
            out.write(
                f"{pad}{prefix}{loc.type.cpp} {loc.name}"
                f"{{{{{lowers}}}, {{{extents}}}}};"
            )
        else:
            out.write(f"{pad}{prefix}{loc.type.cpp} {loc.name}{{{{{extents}}}}};")
        _emit_trailing(out, loc.trailing_comments)
        return
    if loc.type.is_pointer and not loc.type.is_array and loc.initializer is None:
        # Scalar pointer (T*) starts disassociated.
        out.write(f"{pad}{prefix}{loc.type.cpp} {loc.name} = nullptr;")
        _emit_trailing(out, loc.trailing_comments)
        return
    # An assumed-length CHARACTER local (only arises for an ENTRY-shared
    # dummy that isn't this entry's argument) is a character view, not a
    # ``std::string_view`` value — emit it as ``CharRef`` so substring
    # indexing ``s(i, j)`` and write-through still type-check.
    cpp = (
        "fortran::CharRef"
        if not loc.type.is_array and loc.type.cpp == "std::string_view"
        else loc.type.cpp
    )
    out.write(f"{pad}{prefix}{cpp} {loc.name}")
    if loc.initializer is not None:
        out.write(f" = {_render_expr(loc.initializer)}")
    else:
        # Value-initialize so scalars zero out, derived-type structs
        # default-construct, and FortranString fills with blanks —
        # matching Fortran's typical default-initialization behavior.
        out.write("{}")
    out.write(";")
    _emit_trailing(out, loc.trailing_comments)


def _ends_with_return(body: list[IRStatement]) -> bool:
    return bool(body) and isinstance(body[-1], IRReturn)


# ---------------------------------------------------------------------------
# Statements
# ---------------------------------------------------------------------------


def _emit_statement(out: StringIO, stmt: IRStatement, *, indent: int) -> None:
    pad = "  " * indent
    if isinstance(stmt, IRComment):
        _emit_comment_block(out, stmt.comments, indent=indent)
        return
    if isinstance(stmt, IRAssignment):
        _emit_comment_block(out, stmt.leading_comments, indent=indent)
        out.write(f"{pad}{_render_expr(stmt.target)} = {_render_expr(stmt.value)};")
        _emit_trailing(out, stmt.trailing_comments)
        return
    if isinstance(stmt, IRCall):
        _emit_comment_block(out, stmt.leading_comments, indent=indent)
        out.write(f"{pad}{stmt.callee}(")
        out.write(", ".join(_render_expr(a) for a in stmt.args))
        out.write(");")
        _emit_trailing(out, stmt.trailing_comments)
        return
    if isinstance(stmt, IRPrint):
        if stmt.internal_unit is not None:
            _emit_internal_write(out, stmt, indent=indent)
            return
        if any(isinstance(it, IRImpliedDo) for it in stmt.items):
            # A formatted WRITE with implied-do items: expand the
            # implied-do at translation time when its bounds are integer
            # literals.  This lets the existing format renderer (with its
            # array-element overloads of fmt_E / fmt_F / ...) handle the
            # mixed item list as a flat sequence.  Falls back to the
            # list-directed implied-do emitter when no format is in play.
            if stmt.format is not None or stmt.format_expr is not None:
                expanded = _expand_constant_implied_dos(list(stmt.items))
                if expanded is not None:
                    stmt = IRPrint(
                        items=expanded,
                        stream=stmt.stream,
                        format=stmt.format,
                        format_expr=stmt.format_expr,
                        internal_unit=stmt.internal_unit,
                        leading_comments=stmt.leading_comments,
                        trailing_comments=stmt.trailing_comments,
                    )
                else:
                    # Implied-do bounds aren't compile-time constants:
                    # route through the runtime format interpreter, which
                    # cycles the format string over a runtime-built
                    # ``std::vector<FmtArg>`` so each item gets the right
                    # descriptor regardless of when the loop's count is
                    # known.  ``vformat_record`` then renders the cycled
                    # record into the output stream.
                    _emit_runtime_formatted_implied_do(
                        out, stmt, indent=indent
                    )
                    return
            else:
                _emit_io_with_implied_do(out, stmt, write=True, indent=indent)
                return
        _emit_comment_block(out, stmt.leading_comments, indent=indent)
        out.write(f"{pad}{stmt.stream}")
        suppress_nl = False
        if stmt.format_expr is not None:
            # Run-time FORMAT: interpret it against the items at run time.
            out.write(f" << {_render_format_record(stmt)}")
        elif stmt.format is not None:
            suppress_nl = _emit_formatted_chunks(out, stmt)
        else:
            # List-directed: separate items with a single space.
            for i, item in enumerate(stmt.items):
                if i > 0:
                    out.write(" << ' '")
                out.write(f" << {_render_expr(item)}")
        if suppress_nl:
            out.write(";")
        else:
            out.write(" << '\\n';")
        _emit_trailing(out, stmt.trailing_comments)
        return
    if isinstance(stmt, IRDirectRead):
        _emit_comment_block(out, stmt.leading_comments, indent=indent)
        out.write(f"{pad}{{\n")
        out.write(
            f"{pad}  std::string _rec{{_units.read_record({stmt.unit_text}, "
            f"{_render_expr(stmt.rec)})}};\n"
        )
        for target, kind, off, width, dec in stmt.fields:
            tgt = _render_expr(target)
            if kind == "int":
                out.write(
                    f"{pad}  {tgt} = static_cast<std::int32_t>("
                    f"fortran::io::read_field_int(_rec, {off}, {width}));\n"
                )
            else:
                out.write(
                    f"{pad}  {tgt} = static_cast<float>("
                    f"fortran::io::read_field_real(_rec, {off}, {width}, {dec}));\n"
                )
        out.write(f"{pad}}}")
        _emit_trailing(out, stmt.trailing_comments)
        return
    if isinstance(stmt, IRDirectWrite):
        _emit_comment_block(out, stmt.leading_comments, indent=indent)
        # Build the formatted record into a string, then place it at the
        # target record.  ``_emit_formatted_chunks`` is duck-typed on
        # ``.format`` / ``.items``, which IRDirectWrite also carries.
        out.write(f"{pad}{{\n")
        out.write(f"{pad}  std::ostringstream _wrec;\n")
        out.write(f"{pad}  _wrec")
        _emit_formatted_chunks(out, stmt)  # writes " << ..."
        out.write(";\n")
        out.write(
            f"{pad}  _units.write_record({stmt.unit_text}, "
            f"{_render_expr(stmt.rec)}, _wrec.str());\n"
        )
        out.write(f"{pad}}}")
        _emit_trailing(out, stmt.trailing_comments)
        return
    if isinstance(stmt, IRUnformattedDirectWrite):
        _emit_comment_block(out, stmt.leading_comments, indent=indent)
        # Pack each item onto a raw byte buffer, then place it at the
        # target record (zero-padded / truncated to RECL by the runtime).
        out.write(f"{pad}{{\n")
        out.write(f"{pad}  std::vector<std::byte> _wrec;\n")
        for item in stmt.items:
            _emit_unformatted_item(out, item, "_wrec", read=False, indent=indent + 1)
        out.write(
            f"{pad}  _units.write_record_raw({stmt.unit_text}, "
            f"{_render_expr(stmt.rec)}, _wrec);\n"
        )
        out.write(f"{pad}}}")
        _emit_trailing(out, stmt.trailing_comments)
        return
    if isinstance(stmt, IRUnformattedDirectRead):
        _emit_comment_block(out, stmt.leading_comments, indent=indent)
        # Fetch the whole record as raw bytes, then unpack each item.
        out.write(f"{pad}{{\n")
        out.write(
            f"{pad}  auto _rrec = _units.read_record_raw("
            f"{stmt.unit_text}, {_render_expr(stmt.rec)});\n"
        )
        out.write(f"{pad}  std::size_t _roff = 0;\n")
        for item in stmt.items:
            _emit_unformatted_item(out, item, "_rrec", read=True, indent=indent + 1)
        out.write(f"{pad}}}")
        _emit_trailing(out, stmt.trailing_comments)
        return
    if isinstance(stmt, IRInquire):
        _emit_comment_block(out, stmt.leading_comments, indent=indent)
        # One ``_units.inquire_by_*`` call, then per-output field copies.
        out.write(f"{pad}{{\n")
        call = (
            "inquire_by_unit" if stmt.selector_kind == "unit"
            else "inquire_by_file"
        )
        out.write(
            f"{pad}  auto _inq = _units.{call}({_render_expr(stmt.selector)});\n"
        )
        for field, target in stmt.outputs:
            out.write(f"{pad}  {_render_expr(target)} = _inq.{field};\n")
        out.write(f"{pad}}}")
        _emit_trailing(out, stmt.trailing_comments)
        return
    if isinstance(stmt, IRFilePosition):
        _emit_comment_block(out, stmt.leading_comments, indent=indent)
        out.write(
            f"{pad}_units.{stmt.op}({_render_expr(stmt.unit)});"
        )
        _emit_trailing(out, stmt.trailing_comments)
        return
    if isinstance(stmt, IRRead):
        if stmt.internal_unit is not None:
            _emit_internal_read(out, stmt, indent=indent)
            return
        if stmt.fields is not None and stmt.unit_text is not None:
            _emit_formatted_sequential_read(out, stmt, indent=indent)
            return
        if any(isinstance(it, IRImpliedDo) for it in stmt.items):
            _emit_io_with_implied_do(out, stmt, write=False, indent=indent)
            return
        _emit_comment_block(out, stmt.leading_comments, indent=indent)
        if not stmt.items:
            # READ(unit, *) with no item list — Fortran reads-and-discards
            # a whole record.  In C++ that means skip to and past the next
            # newline on the stream.
            out.write(
                f"{pad}{stmt.stream}.ignore("
                f"std::numeric_limits<std::streamsize>::max(), '\\n');"
            )
            _emit_trailing(out, stmt.trailing_comments)
            return
        # List-directed READ: route each item through ``read_list_item``
        # so Fortran's "current value preserved on /" semantics survive
        # C++11's "zero target on failure" behavior.  Short-circuit via
        # ``&&`` so once one item fails (e.g. a ``/`` terminator), the
        # remaining items keep their previous values rather than each
        # consuming further input.
        item_calls = " && ".join(
            f"fortran::io::read_list_item({stmt.stream}, {_render_expr(item)})"
            for item in stmt.items
        )
        if item_calls:
            out.write(f"{pad}(void)({item_calls});")
        # Once the items are filled (or terminated), advance to the next
        # record so the next READ starts on a fresh line.  Clear the
        # failbit too, but preserve eofbit so a well-formed EOF still
        # trips ``END=``-labelled jumps.
        out.write(
            f"\n{pad}if ({stmt.stream}.fail() && !{stmt.stream}.eof()) "
            f"{stmt.stream}.clear();"
        )
        out.write(
            f"\n{pad}{stmt.stream}.ignore("
            f"std::numeric_limits<std::streamsize>::max(), '\\n');"
        )
        _emit_trailing(out, stmt.trailing_comments)
        return
    if isinstance(stmt, IRStop):
        _emit_stop(out, stmt, indent=indent)
        return
    if isinstance(stmt, IRAllocate):
        _emit_comment_block(out, stmt.leading_comments, indent=indent)
        if not stmt.cpp_type:
            raise ConversionError(
                "ALLOCATE", note=f"could not resolve type of {stmt.obj!r}"
            )
        extents = ", ".join(_render_expr(e) for e in stmt.extents)
        if stmt.lowers:
            lowers = ", ".join(_render_expr(e) for e in stmt.lowers)
            out.write(
                f"{pad}{stmt.obj} = {stmt.cpp_type}({{{lowers}}}, {{{extents}}});"
            )
        else:
            out.write(f"{pad}{stmt.obj} = {stmt.cpp_type}({{{extents}}});")
        _emit_trailing(out, stmt.trailing_comments)
        return
    if isinstance(stmt, IRDeallocate):
        _emit_comment_block(out, stmt.leading_comments, indent=indent)
        out.write(f"{pad}{stmt.obj}.deallocate();")
        _emit_trailing(out, stmt.trailing_comments)
        return
    if isinstance(stmt, IRPointerAssign):
        _emit_comment_block(out, stmt.leading_comments, indent=indent)
        if stmt.target is None:
            # nullify / => null()
            rhs = "{}" if stmt.is_array else "nullptr"
            out.write(f"{pad}{stmt.pointer} = {rhs};")
        elif stmt.is_array:
            # Fortran ``p => target(...)``: rebind ``p``'s view to the
            # target's storage (share, don't copy elements).  Use the
            # ArrayRef rebind method explicitly because ``=`` now does
            # element-wise copy (the IRI ``read_data_SD`` semantics).
            out.write(
                f"{pad}{stmt.pointer}.rebind({_render_expr(stmt.target)});"
            )
        else:
            rhs = f"&{_render_expr(stmt.target)}"  # take target's address
            out.write(f"{pad}{stmt.pointer} = {rhs};")
        _emit_trailing(out, stmt.trailing_comments)
        return
    if isinstance(stmt, IRReturn):
        _emit_comment_block(out, stmt.leading_comments, indent=indent)
        if stmt.value is None:
            out.write(f"{pad}return;")
        else:
            out.write(f"{pad}return {_render_expr(stmt.value)};")
        _emit_trailing(out, stmt.trailing_comments)
        return
    if isinstance(stmt, IRIf):
        _emit_if(out, stmt, indent=indent)
        return
    if isinstance(stmt, IRDo):
        _emit_do(out, stmt, indent=indent)
        return
    if isinstance(stmt, IRWhile):
        _emit_while(out, stmt, indent=indent)
        return
    if isinstance(stmt, IRSelectCase):
        _emit_select_case(out, stmt, indent=indent)
        return
    if isinstance(stmt, IRCycle):
        _emit_comment_block(out, stmt.leading_comments, indent=indent)
        out.write(f"{pad}continue;")
        _emit_trailing(out, stmt.trailing_comments)
        return
    if isinstance(stmt, IRExit):
        _emit_comment_block(out, stmt.leading_comments, indent=indent)
        out.write(f"{pad}break;")
        _emit_trailing(out, stmt.trailing_comments)
        return
    if isinstance(stmt, IRBlock):
        _emit_block(out, stmt, indent=indent)
        return
    if isinstance(stmt, IRUnsupported):
        _emit_unsupported(out, stmt, indent=indent)
        return
    raise ConversionError(
        type(stmt).__name__, note="unhandled IR statement"
    )


def _emit_block(out: StringIO, node: IRBlock, *, indent: int) -> None:
    pad = "  " * indent
    _emit_comment_block(out, node.leading_comments, indent=indent)
    out.write(f"{pad}{{\n")
    # ASSOCIATE bindings (auto&& binds to lvalue or rvalue selectors).
    for name, expr in node.bindings:
        out.write(f"{pad}  auto&& {name} = {_render_expr(expr)};\n")
    # BLOCK local declarations.
    for loc in node.locals:
        _emit_local(out, loc, indent=indent + 1)
    for s in node.body:
        _emit_statement(out, s, indent=indent + 1)
    out.write(f"{pad}}}\n")
    _emit_trailing(out, node.trailing_comments)


def _expand_constant_implied_dos(items: list[IRExpr]) -> list[IRExpr] | None:
    """Expand IRImpliedDo entries with integer-literal bounds into a flat
    item list, substituting the loop variable with each integer value.

    Returns the expanded list, or ``None`` if any implied-do has bounds
    the translator can't resolve at compile time."""
    from .transform import map_expr

    def lit_int(e: IRExpr) -> int | None:
        if isinstance(e, IRLiteral):
            try:
                return int(e.cpp_text)
            except ValueError:
                return None
        return None

    def substitute(expr: IRExpr, var: str, value: int) -> IRExpr:
        def swap(e: IRExpr) -> IRExpr:
            if isinstance(e, IRName) and e.name == var:
                return IRLiteral(cpp_text=str(value))
            return e
        return map_expr(expr, swap)

    out: list[IRExpr] = []
    for it in items:
        if isinstance(it, IRImpliedDo):
            lo = lit_int(it.lower)
            hi = lit_int(it.upper)
            step = lit_int(it.step) if it.step is not None else 1
            if lo is None or hi is None or step is None or step == 0:
                return None
            inner_expanded = _expand_constant_implied_dos(list(it.items))
            if inner_expanded is None:
                return None
            i = lo
            while (step > 0 and i <= hi) or (step < 0 and i >= hi):
                for sub in inner_expanded:
                    out.append(substitute(sub, it.var, i))
                i += step
        else:
            out.append(it)
    return out


def _emit_formatted_chunks(out: StringIO, stmt: "IRPrint") -> bool:
    """Emit the ``<< ...`` chain for a format-directed print/write.

    A format the parser can't model is an error, not a silent
    degradation: list-directed output would print the right values with
    the wrong layout, which is exactly the kind of quietly-wrong result
    we refuse to emit.

    Returns ``True`` if the FORMAT requested newline suppression (``$``)
    so the caller knows to skip its trailing ``<< '\\n'``.
    """
    from .format import FormatParseError, render_format

    assert stmt.format is not None
    item_exprs = [_render_expr(it) for it in stmt.items]
    try:
        chunks, suppress_nl = render_format(stmt.format, item_exprs)
    except FormatParseError as exc:
        raise ConversionError(
            "FORMAT", note=str(exc), source=stmt.format
        ) from exc
    for chunk in chunks:
        out.write(f" << {chunk}")
    return suppress_nl


def _emit_internal_write(out: StringIO, stmt: "IRPrint", *, indent: int) -> None:
    """Internal-file write: build the formatted record in a string stream
    and assign it to the character-variable unit (no trailing newline —
    a scalar character unit holds exactly one record)."""
    pad = "  " * indent
    _emit_comment_block(out, stmt.leading_comments, indent=indent)
    unit = _render_expr(stmt.internal_unit)
    if stmt.format_expr is not None:
        # Run-time FORMAT: build the record via the runtime interpreter and
        # assign it directly (no intermediate ostringstream needed).
        out.write(f"{pad}{unit} = {_render_format_record(stmt)};")
        _emit_trailing(out, stmt.trailing_comments)
        return
    out.write(f"{pad}{{\n")
    out.write(f"{pad}  std::ostringstream _ftn_os;\n")
    out.write(f"{pad}  _ftn_os")
    if stmt.format is not None:
        _emit_formatted_chunks(out, stmt)
    else:
        for i, item in enumerate(stmt.items):
            if i > 0:
                out.write(" << ' '")
            out.write(f" << {_render_expr(item)}")
    out.write(";\n")
    out.write(f"{pad}  {unit} = _ftn_os.str();\n")
    out.write(f"{pad}}}")
    _emit_trailing(out, stmt.trailing_comments)


def _render_format_record(stmt: "IRPrint") -> str:
    """Render a ``fortran::io::format_record(fmt, items...)`` call for a
    run-time (non-constant) FORMAT.  The first argument is the format
    string expression; the rest are the output items, flattened."""
    assert stmt.format_expr is not None
    args = [_render_expr(stmt.format_expr)]
    args.extend(_render_expr(it) for it in stmt.items)
    return f"fortran::io::format_record({', '.join(args)})"


def _emit_formatted_sequential_read(
    out: StringIO, stmt: "IRRead", *, indent: int
) -> None:
    """Sequential ``READ(unit, fmt)`` with a fixed-width FORMAT (e.g.
    ``FORMAT(3I3,9I3,I3,3F5.1)``).  Reads one record via ``getline`` per
    format cycle and slices each item by its pre-resolved offset/width
    using ``read_field_int`` / ``read_field_real`` -- matching Fortran's
    column-positional semantics instead of the ``>>`` chain's
    space-tokenizing.

    When the item list exceeds the format's data-descriptor count the
    format cycles to a new record (MSIS-86 reads its 1464-element
    coefficient table with ``FORMAT(1X,5E13.6)`` over 293 lines).
    Each record in ``stmt.fields`` is one such getline + per-field slice
    block."""
    assert stmt.fields is not None and stmt.unit_text is not None
    pad = "  " * indent
    _emit_comment_block(out, stmt.leading_comments, indent=indent)
    out.write(f"{pad}{{\n")
    out.write(f"{pad}  std::string _rec;\n")
    for record in stmt.fields:
        out.write(
            f"{pad}  std::getline(_units.in({stmt.unit_text}), _rec);\n"
        )
        for target, kind, off, width, dec in record:
            tgt = _render_expr(target)
            if kind == "int":
                out.write(
                    f"{pad}  {tgt} = static_cast<std::int32_t>("
                    f"fortran::io::read_field_int(_rec, {off}, {width}));\n"
                )
            else:
                out.write(
                    f"{pad}  {tgt} = static_cast<float>("
                    f"fortran::io::read_field_real(_rec, {off}, {width}, {dec}));\n"
                )
    out.write(f"{pad}}}")
    _emit_trailing(out, stmt.trailing_comments)


def _emit_internal_read(out: StringIO, stmt: "IRRead", *, indent: int) -> None:
    """Internal-file read: parse items from the character-variable unit
    via a string stream."""
    pad = "  " * indent
    _emit_comment_block(out, stmt.leading_comments, indent=indent)
    unit = _render_expr(stmt.internal_unit)
    out.write(f"{pad}{{\n")
    out.write(
        f"{pad}  std::istringstream _ftn_is{{std::string{{std::string_view{{{unit}}}}}}};\n"
    )
    out.write(f"{pad}  _ftn_is")
    for item in stmt.items:
        out.write(f" >> {_render_expr(item)}")
    out.write(";\n")
    out.write(f"{pad}}}")
    _emit_trailing(out, stmt.trailing_comments)


def _emit_unformatted_item(
    out, item, rec_var: str, *, read: bool, indent: int
) -> None:
    """Emit one item of an unformatted direct READ/WRITE.

    Plain items become a single ``take_bytes`` / ``append_bytes`` call.
    An implied-do becomes a runtime for-loop that iterates over its
    inner items -- mirrors the order Fortran would serialize them in
    (innermost loop fastest, items in declaration order)."""
    pad = "  " * indent
    if isinstance(item, IRImpliedDo):
        lo = _render_expr(item.lower)
        hi = _render_expr(item.upper)
        step = _render_expr(item.step) if item.step is not None else "1"
        v = item.var
        out.write(
            f"{pad}for (std::int32_t {v} = {lo}; {v} <= {hi}; {v} += {step}) {{\n"
        )
        for inner in item.items:
            _emit_unformatted_item(
                out, inner, rec_var, read=read, indent=indent + 1
            )
        out.write(f"{pad}}}\n")
        return
    if read:
        out.write(
            f"{pad}_roff = fortran::io::take_bytes({rec_var}, _roff, "
            f"{_render_expr(item)});\n"
        )
    else:
        out.write(
            f"{pad}fortran::io::append_bytes({rec_var}, "
            f"{_render_expr(item)});\n"
        )


def _emit_runtime_formatted_implied_do(
    out: StringIO, stmt: "IRPrint", *, indent: int
) -> None:
    """Emit a formatted WRITE with runtime-bounded implied-do items via
    the runtime format interpreter.  Builds a ``std::vector<FmtArg>``
    at run time (scalars push one arg, implied-do items push one per
    iteration), then routes through ``vformat_record(fmt, args)`` which
    cycles the format over the args.
    """
    pad = "  " * indent
    _emit_comment_block(out, stmt.leading_comments, indent=indent)
    out.write(f"{pad}{{\n")
    out.write(f"{pad}  std::vector<fortran::io::FmtArg> _args;\n")

    def push_item(item, ind: int) -> None:
        ipad = "  " * ind
        if isinstance(item, IRImpliedDo):
            var = item.var
            lo = _render_expr(item.lower)
            hi = _render_expr(item.upper)
            step = _render_expr(item.step) if item.step is not None else "1"
            cond = (
                f"{var} <= {hi}" if step == "1"
                else f"({step} >= 0 ? {var} <= {hi} : {var} >= {hi})"
            )
            incr = f"++{var}" if step == "1" else f"{var} += {step}"
            out.write(
                f"{ipad}for (fortran::index_t {var} = {lo}; "
                f"{cond}; {incr}) {{\n"
            )
            for sub in item.items:
                push_item(sub, ind + 1)
            out.write(f"{ipad}}}\n")
        else:
            rendered = _render_expr(item)
            out.write(
                f"{ipad}_args.push_back("
                f"fortran::io::make_fmt_arg({rendered}));\n"
            )

    for it in stmt.items:
        push_item(it, indent + 1)
    if stmt.format_expr is not None:
        fmt_expr = _render_expr(stmt.format_expr)
    else:
        from .format import _cpp_string_literal as _csl
        fmt_expr = _csl(stmt.format)
    out.write(
        f"{pad}  {stmt.stream} << "
        f"fortran::io::vformat_record({fmt_expr}, _args) << '\\n';\n"
    )
    out.write(f"{pad}}}")
    _emit_trailing(out, stmt.trailing_comments)


def _emit_io_with_implied_do(out, stmt, *, write: bool, indent: int) -> None:
    """Emit a print/read whose item list contains an implied-do, as a
    sequence of statements (plain items inline, implied-do items as
    loops).  Used only for the list-directed forms."""
    pad = "  " * indent
    _emit_comment_block(out, stmt.leading_comments, indent=indent)
    stream = stmt.stream
    op = "<<" if write else ">>"

    def emit_item(item, ind: int) -> None:
        ipad = "  " * ind
        if isinstance(item, IRImpliedDo):
            var = item.var
            lo = _render_expr(item.lower)
            hi = _render_expr(item.upper)
            step = _render_expr(item.step) if item.step is not None else "1"
            cond = f"{var} <= {hi}" if step == "1" else (
                f"({step} >= 0 ? {var} <= {hi} : {var} >= {hi})"
            )
            incr = f"++{var}" if step == "1" else f"{var} += {step}"
            out.write(
                f"{ipad}for (fortran::index_t {var} = {lo}; {cond}; {incr}) {{\n"
            )
            for sub in item.items:
                emit_item(sub, ind + 1)
            out.write(f"{ipad}}}\n")
        else:
            rendered = _render_expr(item)
            if write:
                out.write(f"{ipad}{stream} {op} {rendered} {op} ' ';\n")
            else:
                out.write(f"{ipad}{stream} {op} {rendered};\n")

    for it in stmt.items:
        emit_item(it, indent)
    if write:
        out.write(f"{pad}{stream} << '\\n';\n")


def _emit_stop(out: StringIO, stmt: "IRStop", *, indent: int) -> None:
    pad = "  " * indent
    _emit_comment_block(out, stmt.leading_comments, indent=indent)
    # Determine the exit code expression.
    if stmt.code is not None:
        code = _render_expr(stmt.code)
    else:
        code = "1" if stmt.is_error else "0"
    if stmt.message is not None:
        escaped = stmt.message.replace("\\", "\\\\").replace('"', '\\"')
        # Fortran prints the stop message; mirror that on stderr.
        out.write(f'{pad}{{ std::cerr << "{escaped}" << \'\\n\'; '
                  f"std::exit({code}); }}")
    else:
        out.write(f"{pad}std::exit({code});")
    _emit_trailing(out, stmt.trailing_comments)


def _emit_while(out: StringIO, node: IRWhile, *, indent: int) -> None:
    pad = "  " * indent
    _emit_comment_block(out, node.leading_comments, indent=indent)
    out.write(f"{pad}while ({_render_expr(node.condition)}) {{\n")
    for s in node.body:
        _emit_statement(out, s, indent=indent + 1)
    out.write(f"{pad}}}\n")
    _emit_trailing(out, node.trailing_comments)


def _emit_select_case(
    out: StringIO, node: IRSelectCase, *, indent: int
) -> None:
    """Lower SELECT CASE.

    When every clause is a list of literal integer values and/or bounded
    literal-integer ranges of modest total width, emit a real C++
    ``switch`` -- a dense integer SELECT CASE compiles to a jump-table
    rather than the sequential compare chain of an ``if`` chain.
    Otherwise (CHARACTER / LOGICAL selectors, open-ended ranges, wide
    ranges, non-literal bounds) fall back to the if-chain form, which
    handles every case shape Fortran allows.
    """
    if _switch_eligible(node):
        _emit_select_case_switch(out, node, indent=indent)
        return
    _emit_select_case_ifchain(out, node, indent=indent)


# Cap on total case-label expansion for ranged CASE forms.  CASE (1:5) -> 5
# labels, CASE (1, 7, 10:12) -> 5 labels, etc.  Picked so a typical kind-code
# selector (a few dozen values) takes the switch path while a pathological
# CASE (1:1000000) doesn't blow up the .cpp.
_SWITCH_LABEL_BUDGET = 64


def _int_literal_value(expr: IRExpr) -> int | None:
    """Return the integer value of a literal expression, or None."""
    if isinstance(expr, IRLiteral):
        t = expr.cpp_text.strip()
        # Allow a leading sign and an optional kind suffix.
        if t.startswith(("-", "+")):
            sign, body = t[0], t[1:]
        else:
            sign, body = "+", t
        # Strip a C++ literal suffix (``42LL``, ``42L``, ``42U`` etc.).
        while body and body[-1] in "uUlL":
            body = body[:-1]
        if body.isdigit():
            return int(sign + body)
    return None


def _switch_eligible(node: IRSelectCase) -> bool:
    """A SELECT CASE is switch-eligible when every match is a literal
    integer and total label count stays within the budget."""
    if not node.clauses:
        return False
    total = 0
    for clause in node.clauses:
        for v in clause.values:
            if _int_literal_value(v) is None:
                return False
            total += 1
        for lo, hi in clause.ranges:
            lo_v = _int_literal_value(lo) if lo is not None else None
            hi_v = _int_literal_value(hi) if hi is not None else None
            # Open-ended ranges can't be enumerated.
            if lo_v is None or hi_v is None:
                return False
            if hi_v < lo_v:
                # An empty range is fine but adds 0 labels.
                continue
            total += hi_v - lo_v + 1
            if total > _SWITCH_LABEL_BUDGET:
                return False
    return total > 0


def _emit_select_case_switch(
    out: StringIO, node: IRSelectCase, *, indent: int
) -> None:
    pad = "  " * indent
    body_pad = pad + "  "
    case_pad = body_pad + "  "
    _emit_comment_block(out, node.leading_comments, indent=indent)
    out.write(f"{pad}switch ({_render_expr(node.selector)}) {{\n")
    for clause in node.clauses:
        labels: list[int] = []
        for v in clause.values:
            iv = _int_literal_value(v)
            assert iv is not None  # _switch_eligible guarantees this
            labels.append(iv)
        for lo, hi in clause.ranges:
            assert lo is not None and hi is not None
            lo_v = _int_literal_value(lo)
            hi_v = _int_literal_value(hi)
            assert lo_v is not None and hi_v is not None
            labels.extend(range(lo_v, hi_v + 1))
        for label in labels:
            out.write(f"{body_pad}case {label}:\n")
        for s in clause.body:
            _emit_statement(out, s, indent=indent + 2)
        out.write(f"{case_pad}break;\n")
    if node.default_body is not None:
        out.write(f"{body_pad}default:\n")
        for s in node.default_body:
            _emit_statement(out, s, indent=indent + 2)
        out.write(f"{case_pad}break;\n")
    out.write(f"{pad}}}\n")
    _emit_trailing(out, node.trailing_comments)


def _emit_select_case_ifchain(
    out: StringIO, node: IRSelectCase, *, indent: int
) -> None:
    """Fallback for non-integral selectors, open-ended ranges, etc."""
    pad = "  " * indent
    _emit_comment_block(out, node.leading_comments, indent=indent)
    selector_text = _render_expr(node.selector)
    sel = selector_text
    opened_scope = not _is_simple_selector(node.selector)
    if opened_scope:
        # Bind the selector to a local so it's evaluated exactly once.
        out.write(f"{pad}{{\n")
        out.write(f"{pad}  const auto _sel = {selector_text};\n")
        sel = "_sel"
        inner_pad = pad + "  "
        body_indent = indent + 2
    else:
        inner_pad = pad
        body_indent = indent + 1

    first = True
    for clause in node.clauses:
        cond = _case_condition(sel, clause)
        if first:
            out.write(f"{inner_pad}if ({cond}) {{\n")
            first = False
        else:
            out.write(f" else if ({cond}) {{\n")
        for s in clause.body:
            _emit_statement(out, s, indent=body_indent)
        out.write(f"{inner_pad}}}")
    if node.default_body is not None:
        if first:
            # No case clauses, only a default — emit a bare block.
            out.write(f"{inner_pad}{{\n")
        else:
            out.write(" else {\n")
        for s in node.default_body:
            _emit_statement(out, s, indent=body_indent)
        out.write(f"{inner_pad}}}\n")
    else:
        out.write("\n")
    if opened_scope:
        out.write(f"{pad}}}\n")
    _emit_trailing(out, node.trailing_comments)


def _is_simple_selector(expr: IRExpr) -> bool:
    return isinstance(expr, (IRName, IRLiteral))


def _case_condition(sel: str, clause: "IRCaseClause") -> str:
    """Build the boolean test for one case clause."""
    parts: list[str] = []
    for v in clause.values:
        parts.append(f"{sel} == {_render_expr(v)}")
    for lo, hi in clause.ranges:
        if lo is not None and hi is not None:
            parts.append(f"({sel} >= {_render_expr(lo)} && {sel} <= {_render_expr(hi)})")
        elif lo is not None:
            parts.append(f"{sel} >= {_render_expr(lo)}")
        elif hi is not None:
            parts.append(f"{sel} <= {_render_expr(hi)}")
    return " || ".join(parts) if parts else "false"


def _emit_if(out: StringIO, node: IRIf, *, indent: int) -> None:
    pad = "  " * indent
    _emit_comment_block(out, node.leading_comments, indent=indent)
    for i, (cond, body) in enumerate(node.branches):
        keyword = "if" if i == 0 else "else if"
        out.write(f"{pad}{keyword} ({_render_expr(cond)}) {{\n")
        for s in body:
            _emit_statement(out, s, indent=indent + 1)
        out.write(f"{pad}}}")
        if i + 1 < len(node.branches) or node.else_body is not None:
            out.write(" ")
        else:
            out.write("\n")
    if node.else_body is not None:
        out.write("else {\n")
        for s in node.else_body:
            _emit_statement(out, s, indent=indent + 1)
        out.write(f"{pad}}}\n")
    _emit_trailing(out, node.trailing_comments)


def _emit_do(out: StringIO, node: IRDo, *, indent: int) -> None:
    pad = "  " * indent
    _emit_comment_block(out, node.leading_comments, indent=indent)
    var = node.var
    decl = "fortran::index_t " if node.declare else ""
    lo = _render_expr(node.lower)
    hi = _render_expr(node.upper)
    step = _render_expr(node.step) if node.step is not None else "1"
    # For the common step==1 case, write a clean ``i <= hi`` form.
    if step == "1":
        out.write(
            f"{pad}for ({decl}{var} = {lo}; {var} <= {hi}; ++{var}) {{\n"
        )
    else:
        out.write(
            f"{pad}for ({decl}{var} = {lo}; "
            f"({step} >= 0 ? {var} <= {hi} : {var} >= {hi}); "
            f"{var} += {step}) {{\n"
        )
    for s in node.body:
        _emit_statement(out, s, indent=indent + 1)
    out.write(f"{pad}}}\n")
    _emit_trailing(out, node.trailing_comments)


def _emit_unsupported(
    out: StringIO, stmt: IRUnsupported, *, indent: int
) -> None:
    # An IRUnsupported reaching emit means an earlier pass couldn't model
    # the construct.  Fail loudly rather than write a // TODO placeholder.
    raise ConversionError(stmt.kind, note=stmt.note, source=stmt.source_text)


# ---------------------------------------------------------------------------
# Expressions
# ---------------------------------------------------------------------------


def _render_section(expr: "IRSection") -> str:
    """Render a section as a runtime ``a.section(...)`` view.

    A rank-1 single-triplet section emits the scalar ``section(lo, hi,
    stride)`` overload.  Multi-dimensional or mixed sections emit the
    general overload, passing a ``fortran::Slice`` for each kept
    dimension and a plain index for each dropped one."""
    a = expr.array
    triplets = [s for s in expr.subscripts if isinstance(s, IRTriplet)]
    if len(expr.subscripts) == 1 and len(triplets) == 1:
        trip = triplets[0]
        lo = _render_expr(trip.lower) if trip.lower is not None else f"{a}.lbound(1)"
        hi = _render_expr(trip.upper) if trip.upper is not None else f"{a}.ubound(1)"
        if trip.stride is not None:
            return f"{a}.section({lo}, {hi}, {_render_expr(trip.stride)})"
        return f"{a}.section({lo}, {hi})"
    parts: list[str] = []
    for dim, s in enumerate(expr.subscripts, start=1):
        if isinstance(s, IRTriplet):
            lo = _render_expr(s.lower) if s.lower is not None else f"{a}.lbound({dim})"
            hi = _render_expr(s.upper) if s.upper is not None else f"{a}.ubound({dim})"
            stride = _render_expr(s.stride) if s.stride is not None else "1"
            parts.append(f"fortran::Slice{{{lo}, {hi}, {stride}}}")
        else:
            parts.append(_render_expr(s))
    return f"{a}.section({', '.join(parts)})"


def _render_expr(expr: IRExpr) -> str:
    if isinstance(expr, IRLiteral):
        return expr.cpp_text
    if isinstance(expr, IRName):
        return expr.name
    if isinstance(expr, IRBinaryOp):
        return f"{_render_expr(expr.lhs)} {expr.op} {_render_expr(expr.rhs)}"
    if isinstance(expr, IRUnaryOp):
        if expr.op == "()":
            return f"({_render_expr(expr.operand)})"
        return f"{expr.op}{_render_expr(expr.operand)}"
    if isinstance(expr, IRFunctionCall):
        args = ", ".join(_render_expr(a) for a in expr.args)
        return f"{expr.callee}({args})"
    if isinstance(expr, IRMember):
        return f"{_render_expr(expr.base)}.{expr.field}"
    if isinstance(expr, IRSubstr):
        return (
            f"{_render_expr(expr.base)}"
            f"({_render_expr(expr.lo)}, {_render_expr(expr.hi)})"
        )
    if isinstance(expr, IRCast):
        return f"static_cast<{expr.cpp_type}>({_render_expr(expr.operand)})"
    if isinstance(expr, IRArrayConstructor):
        elems = ", ".join(_render_expr(e) for e in expr.elements)
        # Variadic (no braces) so a mixed-literal constructor deduces a
        # common element type rather than a homogeneous initializer_list.
        return f"fortran::array_of({elems})"
    if isinstance(expr, IRLambda):
        params = ", ".join(f"auto {p}" for p in expr.params)
        return f"[&]({params}) {{ return {_render_expr(expr.body)}; }}"
    if isinstance(expr, IRSection):
        return _render_section(expr)
    if isinstance(expr, IRRaw):
        return expr.text
    return f"/* unhandled expr {type(expr).__name__} */"


# ---------------------------------------------------------------------------
# Comment rendering
# ---------------------------------------------------------------------------


def _emit_comment_block(
    out: StringIO, comments: Iterable[Comment], *, indent: int
) -> None:
    pad = "  " * indent
    for c in comments:
        # Strip the leading "!" and any single leading blank that flang
        # left in place, so "// hello" looks like real C++ comments.
        body = c.text
        if body.startswith(" "):
            body = body[1:]
        out.write(f"{pad}// {body.rstrip()}\n")


def _emit_trailing(out: StringIO, comments: Iterable[Comment]) -> None:
    comments = list(comments)
    if not comments:
        out.write("\n")
        return
    first = comments[0]
    body = first.text.lstrip("!").lstrip()
    out.write(f"  // {body.rstrip()}\n")
    for c in comments[1:]:
        out.write(f"  // {c.text.lstrip('!').lstrip().rstrip()}\n")
