"""Render an :mod:`.ir` IRTranslationUnit as C++ source text.

The emitter is purely string-building: it never inspects the original
AST.  It walks the IR top-down, prints subprograms in order, and
preserves comments attached by ``annotate``.

Aim is *readable* C++ — see R8 in the README.  We default to plain
standard-library spellings and only reach into ``fortran::io`` /
``fortran::FortranString`` when the rules say we must.
"""

from __future__ import annotations

from io import StringIO
from typing import Iterable

from flang_ast import Comment

from .ir import (
    IRAssignment,
    IRBinaryOp,
    IRCall,
    IRCaseClause,
    IRComment,
    IRCycle,
    IRDo,
    IRExit,
    IRExpr,
    IRFunctionCall,
    IRIf,
    IRLiteral,
    IRLocal,
    IRMember,
    IRName,
    IRPrint,
    IRRaw,
    IRReturn,
    IRSelectCase,
    IRStateStruct,
    IRStatement,
    IRSubprogram,
    IRTranslationUnit,
    IRType,
    IRUnaryOp,
    IRUnsupported,
    IRWhile,
)


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------


def emit_translation_unit(tu: IRTranslationUnit) -> str:
    """Render the whole translation unit to a single C++ source string."""
    out = StringIO()
    _emit_file_header(out, tu)
    _emit_includes(out, tu)
    # User-defined types first, then module / state structs, so
    # everything below can reference them by name.
    _emit_derived_types(out, tu)
    _emit_module_structs(out, tu)
    _emit_state_structs(out, tu)
    for sub in tu.subprograms:
        out.write("\n")
        _emit_subprogram(out, sub)
    _emit_cpp_main(out, tu)
    return out.getvalue()


def _emit_derived_types(out: StringIO, tu: IRTranslationUnit) -> None:
    if not tu.derived_types:
        return
    out.write("\n// ---- User-defined types ----\n")
    for dt in tu.derived_types:
        out.write(f"\nstruct {dt.cpp_type} {{\n")
        for field_local in dt.fields:
            _emit_local(out, field_local, indent=1)
        out.write("};\n")


def _emit_module_structs(out: StringIO, tu: IRTranslationUnit) -> None:
    modules = [m for m in tu.modules if m.variables]
    if not modules:
        return
    out.write("\n// ---- Module state structs (module variables) ----\n")
    for m in modules:
        out.write(f"\nstruct {m.cpp_type} {{\n")
        for var in m.variables:
            _emit_local(out, var, indent=1)
        out.write("};\n")


def _emit_state_structs(out: StringIO, tu: IRTranslationUnit) -> None:
    if tu.common_structs:
        out.write("\n// ---- Common block structs (shared program state) ----\n")
        for s in tu.common_structs:
            _emit_one_struct(out, s)
    save_structs = [
        s.save_struct for s in tu.subprograms if s.save_struct is not None
    ]
    if save_structs:
        out.write("\n// ---- Per-subprogram state structs (SAVE locals) ----\n")
        for s in save_structs:
            _emit_one_struct(out, s)


def _emit_one_struct(out: StringIO, s: IRStateStruct) -> None:
    out.write(f"\nstruct {s.cpp_type} {{\n")
    for field_local in s.fields:
        # Reuse the local-declaration emitter so types and defaults
        # stay consistent.
        _emit_local(out, field_local, indent=1)
    out.write("};\n")


# ---------------------------------------------------------------------------
# File-level scaffolding
# ---------------------------------------------------------------------------


def _emit_file_header(out: StringIO, tu: IRTranslationUnit) -> None:
    out.write("// Generated by fortran-to-cpp.\n")
    if tu.source_file:
        out.write(f"// Source: {tu.source_file}\n")
    out.write("//\n")
    out.write("// This file follows the rules in flang/tools/fortran-to-cpp/README.md.\n")
    out.write("// Edit the original Fortran source rather than the generated C++.\n\n")


def _emit_includes(out: StringIO, tu: IRTranslationUnit) -> None:
    # For now we include the kitchen sink (cmath for intrinsics, format
    # for inline std::format calls).  Once the IR carries enough info
    # we can prune this on a per-translation-unit basis.
    includes = {"<algorithm>", "<cmath>", "<cstdint>", "<format>",
                "<iostream>", "<string_view>",
                '"fortran/runtime.hpp"'}
    for inc in sorted(includes):
        out.write(f"#include {inc}\n")
    out.write("\nusing namespace std::string_view_literals;\n")


def _emit_cpp_main(out: StringIO, tu: IRTranslationUnit) -> None:
    """If a MainProgram exists, generate a C++ ``main`` that calls it.

    Subprograms-only translation units don't need a main.
    """
    main_progs = [s for s in tu.subprograms if s.kind == "main"]
    if not main_progs:
        return
    main = main_progs[0]
    out.write("\nint main() {\n")
    out.write(f"  {main.name}();\n")
    out.write("  return 0;\n")
    out.write("}\n")


# ---------------------------------------------------------------------------
# Subprograms
# ---------------------------------------------------------------------------


def _emit_subprogram(out: StringIO, sub: IRSubprogram) -> None:
    _emit_comment_block(out, sub.leading_comments, indent=0)
    # Signature
    if sub.kind == "main":
        out.write(f"void {sub.name}(")
    elif sub.kind == "function":
        ret = sub.return_type.cpp if sub.return_type else "void"
        out.write(f"{ret} {sub.name}(")
    else:  # subroutine
        out.write(f"void {sub.name}(")
    # State parameters first (D2.b — granular per-routine state),
    # then the user-visible Fortran dummy args.
    parts = [f"{sp.struct_type}& {sp.name}" for sp in sub.state_params]
    parts.extend(p.cpp_param_decl() for p in sub.parameters)
    out.write(", ".join(parts))
    out.write(") {\n")

    # Local variable declarations.
    for loc in sub.locals:
        _emit_local(out, loc, indent=1)
    if sub.locals and sub.body:
        out.write("\n")

    # Body.
    for stmt in sub.body:
        _emit_statement(out, stmt, indent=1)

    # For a function with no explicit return: emit one based on the
    # local variable that shared the function name (which lowering
    # has already renamed to ``<name>_result``).
    if sub.kind == "function" and sub.return_type is not None:
        if not _ends_with_return(sub.body):
            if sub.body:
                out.write("\n")
            out.write(f"  return {sub.name}_result;\n")

    out.write("}\n")


def _emit_local(out: StringIO, loc: IRLocal, *, indent: int) -> None:
    pad = "  " * indent
    _emit_comment_block(out, loc.leading_comments, indent=indent)
    prefix = "constexpr " if loc.is_parameter else ""
    if loc.type.is_array and loc.initializer is None:
        # ``fortran::Array<T, R> name({ext1, ext2, ...});`` — using the
        # extent-only constructor when no explicit lower bounds were
        # given, and the (lower-bounds, extents) constructor otherwise.
        out.write(f"{pad}{prefix}{loc.type.cpp} {loc.name}(")
        if loc.type.array_lower_bound_exprs:
            lowers = ", ".join(loc.type.array_lower_bound_exprs)
            extents = ", ".join(loc.type.array_extent_exprs)
            out.write(f"{{{lowers}}}, {{{extents}}}")
        else:
            extents = ", ".join(loc.type.array_extent_exprs)
            out.write(f"{{{extents}}}")
        out.write(");")
        _emit_trailing(out, loc.trailing_comments)
        return
    out.write(f"{pad}{prefix}{loc.type.cpp} {loc.name}")
    if loc.initializer is not None:
        out.write(f" = {_render_expr(loc.initializer)}")
    else:
        # Value-initialize so scalars zero out, derived-type structs
        # default-construct, and FortranString fills with blanks —
        # matching Fortran's typical default-initialization behavior.
        out.write("{}")
    out.write(";")
    _emit_trailing(out, loc.trailing_comments)


def _ends_with_return(body: list[IRStatement]) -> bool:
    return bool(body) and isinstance(body[-1], IRReturn)


# ---------------------------------------------------------------------------
# Statements
# ---------------------------------------------------------------------------


def _emit_statement(out: StringIO, stmt: IRStatement, *, indent: int) -> None:
    pad = "  " * indent
    if isinstance(stmt, IRComment):
        _emit_comment_block(out, stmt.comments, indent=indent)
        return
    if isinstance(stmt, IRAssignment):
        _emit_comment_block(out, stmt.leading_comments, indent=indent)
        out.write(f"{pad}{_render_expr(stmt.target)} = {_render_expr(stmt.value)};")
        _emit_trailing(out, stmt.trailing_comments)
        return
    if isinstance(stmt, IRCall):
        _emit_comment_block(out, stmt.leading_comments, indent=indent)
        out.write(f"{pad}{stmt.callee}(")
        out.write(", ".join(_render_expr(a) for a in stmt.args))
        out.write(");")
        _emit_trailing(out, stmt.trailing_comments)
        return
    if isinstance(stmt, IRPrint):
        _emit_comment_block(out, stmt.leading_comments, indent=indent)
        out.write(f"{pad}{stmt.stream}")
        if stmt.format is not None:
            _emit_formatted_chunks(out, stmt)
        else:
            # List-directed: separate items with a single space.
            for i, item in enumerate(stmt.items):
                if i > 0:
                    out.write(" << ' '")
                out.write(f" << {_render_expr(item)}")
        out.write(" << '\\n';")
        _emit_trailing(out, stmt.trailing_comments)
        return
    if isinstance(stmt, IRReturn):
        _emit_comment_block(out, stmt.leading_comments, indent=indent)
        if stmt.value is None:
            out.write(f"{pad}return;")
        else:
            out.write(f"{pad}return {_render_expr(stmt.value)};")
        _emit_trailing(out, stmt.trailing_comments)
        return
    if isinstance(stmt, IRIf):
        _emit_if(out, stmt, indent=indent)
        return
    if isinstance(stmt, IRDo):
        _emit_do(out, stmt, indent=indent)
        return
    if isinstance(stmt, IRWhile):
        _emit_while(out, stmt, indent=indent)
        return
    if isinstance(stmt, IRSelectCase):
        _emit_select_case(out, stmt, indent=indent)
        return
    if isinstance(stmt, IRCycle):
        _emit_comment_block(out, stmt.leading_comments, indent=indent)
        out.write(f"{pad}continue;")
        _emit_trailing(out, stmt.trailing_comments)
        return
    if isinstance(stmt, IRExit):
        _emit_comment_block(out, stmt.leading_comments, indent=indent)
        out.write(f"{pad}break;")
        _emit_trailing(out, stmt.trailing_comments)
        return
    if isinstance(stmt, IRUnsupported):
        _emit_unsupported(out, stmt, indent=indent)
        return
    out.write(f"{pad}// TODO: unhandled IR statement {type(stmt).__name__}\n")


def _emit_formatted_chunks(out: StringIO, stmt: "IRPrint") -> None:
    """Emit the ``<< ...`` chain for a format-directed print/write.

    Falls back to list-directed output (with a TODO note) when the
    format string uses a feature the parser doesn't model yet.
    """
    from .format import FormatParseError, render_format

    assert stmt.format is not None
    item_exprs = [_render_expr(it) for it in stmt.items]
    try:
        chunks = render_format(stmt.format, item_exprs)
    except FormatParseError as exc:
        # Couldn't parse — degrade gracefully to list-directed, leaving
        # a marker so the user knows fidelity wasn't achieved.
        out.write(f" /* TODO: format {stmt.format!r}: {exc} */")
        for i, expr in enumerate(item_exprs):
            if i > 0:
                out.write(" << ' '")
            out.write(f" << {expr}")
        return
    for chunk in chunks:
        out.write(f" << {chunk}")


def _emit_while(out: StringIO, node: IRWhile, *, indent: int) -> None:
    pad = "  " * indent
    _emit_comment_block(out, node.leading_comments, indent=indent)
    out.write(f"{pad}while ({_render_expr(node.condition)}) {{\n")
    for s in node.body:
        _emit_statement(out, s, indent=indent + 1)
    out.write(f"{pad}}}\n")
    _emit_trailing(out, node.trailing_comments)


def _emit_select_case(
    out: StringIO, node: IRSelectCase, *, indent: int
) -> None:
    """Lower select-case to an if / else-if chain.

    A switch would read more naturally for the pure integer-list case,
    but Fortran case ranges (``case (1:5)``) and character selectors
    don't map onto C++ switch, so an if-chain keeps one code path that
    is always correct.  When the selector isn't a trivial name we bind
    it to a local so it's evaluated once.
    """
    pad = "  " * indent
    _emit_comment_block(out, node.leading_comments, indent=indent)
    selector_text = _render_expr(node.selector)
    sel = selector_text
    opened_scope = not _is_simple_selector(node.selector)
    if opened_scope:
        # Bind the selector to a local so it's evaluated exactly once.
        out.write(f"{pad}{{\n")
        out.write(f"{pad}  const auto _sel = {selector_text};\n")
        sel = "_sel"
        inner_pad = pad + "  "
        body_indent = indent + 2
    else:
        inner_pad = pad
        body_indent = indent + 1

    first = True
    for clause in node.clauses:
        cond = _case_condition(sel, clause)
        if first:
            out.write(f"{inner_pad}if ({cond}) {{\n")
            first = False
        else:
            out.write(f" else if ({cond}) {{\n")
        for s in clause.body:
            _emit_statement(out, s, indent=body_indent)
        out.write(f"{inner_pad}}}")
    if node.default_body is not None:
        if first:
            # No case clauses, only a default — emit a bare block.
            out.write(f"{inner_pad}{{\n")
        else:
            out.write(" else {\n")
        for s in node.default_body:
            _emit_statement(out, s, indent=body_indent)
        out.write(f"{inner_pad}}}\n")
    else:
        out.write("\n")
    if opened_scope:
        out.write(f"{pad}}}\n")
    _emit_trailing(out, node.trailing_comments)


def _is_simple_selector(expr: IRExpr) -> bool:
    return isinstance(expr, (IRName, IRLiteral))


def _case_condition(sel: str, clause: "IRCaseClause") -> str:
    """Build the boolean test for one case clause."""
    parts: list[str] = []
    for v in clause.values:
        parts.append(f"{sel} == {_render_expr(v)}")
    for lo, hi in clause.ranges:
        if lo is not None and hi is not None:
            parts.append(f"({sel} >= {_render_expr(lo)} && {sel} <= {_render_expr(hi)})")
        elif lo is not None:
            parts.append(f"{sel} >= {_render_expr(lo)}")
        elif hi is not None:
            parts.append(f"{sel} <= {_render_expr(hi)}")
    return " || ".join(parts) if parts else "false"


def _emit_if(out: StringIO, node: IRIf, *, indent: int) -> None:
    pad = "  " * indent
    _emit_comment_block(out, node.leading_comments, indent=indent)
    for i, (cond, body) in enumerate(node.branches):
        keyword = "if" if i == 0 else "else if"
        out.write(f"{pad}{keyword} ({_render_expr(cond)}) {{\n")
        for s in body:
            _emit_statement(out, s, indent=indent + 1)
        out.write(f"{pad}}}")
        if i + 1 < len(node.branches) or node.else_body is not None:
            out.write(" ")
        else:
            out.write("\n")
    if node.else_body is not None:
        out.write("else {\n")
        for s in node.else_body:
            _emit_statement(out, s, indent=indent + 1)
        out.write(f"{pad}}}\n")
    _emit_trailing(out, node.trailing_comments)


def _emit_do(out: StringIO, node: IRDo, *, indent: int) -> None:
    pad = "  " * indent
    _emit_comment_block(out, node.leading_comments, indent=indent)
    var = node.var
    lo = _render_expr(node.lower)
    hi = _render_expr(node.upper)
    step = _render_expr(node.step) if node.step is not None else "1"
    # For the common step==1 case, write a clean ``i <= hi`` form.
    if step == "1":
        out.write(
            f"{pad}for ({var} = {lo}; {var} <= {hi}; ++{var}) {{\n"
        )
    else:
        out.write(
            f"{pad}for ({var} = {lo}; "
            f"({step} >= 0 ? {var} <= {hi} : {var} >= {hi}); "
            f"{var} += {step}) {{\n"
        )
    for s in node.body:
        _emit_statement(out, s, indent=indent + 1)
    out.write(f"{pad}}}\n")
    _emit_trailing(out, node.trailing_comments)


def _emit_unsupported(
    out: StringIO, stmt: IRUnsupported, *, indent: int
) -> None:
    pad = "  " * indent
    _emit_comment_block(out, stmt.leading_comments, indent=indent)
    out.write(f"{pad}// TODO: fortran-to-cpp does not yet translate "
              f"{stmt.kind}\n")
    if stmt.note:
        out.write(f"{pad}//       {stmt.note}\n")
    for line in stmt.source_text.splitlines() or [stmt.source_text]:
        out.write(f"{pad}//   {line.rstrip()}\n")


# ---------------------------------------------------------------------------
# Expressions
# ---------------------------------------------------------------------------


def _render_expr(expr: IRExpr) -> str:
    if isinstance(expr, IRLiteral):
        return expr.cpp_text
    if isinstance(expr, IRName):
        return expr.name
    if isinstance(expr, IRBinaryOp):
        return f"{_render_expr(expr.lhs)} {expr.op} {_render_expr(expr.rhs)}"
    if isinstance(expr, IRUnaryOp):
        if expr.op == "()":
            return f"({_render_expr(expr.operand)})"
        return f"{expr.op}{_render_expr(expr.operand)}"
    if isinstance(expr, IRFunctionCall):
        args = ", ".join(_render_expr(a) for a in expr.args)
        return f"{expr.callee}({args})"
    if isinstance(expr, IRMember):
        return f"{_render_expr(expr.base)}.{expr.field}"
    if isinstance(expr, IRRaw):
        return expr.text
    return f"/* unhandled expr {type(expr).__name__} */"


# ---------------------------------------------------------------------------
# Comment rendering
# ---------------------------------------------------------------------------


def _emit_comment_block(
    out: StringIO, comments: Iterable[Comment], *, indent: int
) -> None:
    pad = "  " * indent
    for c in comments:
        # Strip the leading "!" and any single leading blank that flang
        # left in place, so "// hello" looks like real C++ comments.
        body = c.text
        if body.startswith(" "):
            body = body[1:]
        out.write(f"{pad}// {body.rstrip()}\n")


def _emit_trailing(out: StringIO, comments: Iterable[Comment]) -> None:
    comments = list(comments)
    if not comments:
        out.write("\n")
        return
    first = comments[0]
    body = first.text.lstrip("!").lstrip()
    out.write(f"  // {body.rstrip()}\n")
    for c in comments[1:]:
        out.write(f"  // {c.text.lstrip('!').lstrip().rstrip()}\n")
