//===-- fortran/io.hpp - Format-fidelity helpers ----------------*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// fortran::io
//
// Helper functions for Fortran edit descriptors that can **not** be
// expressed directly in ``std::format``.  Generated code uses
// ``std::format`` inline whenever the format spec is expressible —
// the emitter only falls through to these helpers for the genuinely
// awkward cases:
//
//   G       — general numeric format
//   P       — scale factor
//   T, TL,  — absolute / left / right tab control
//   TR
//   S, SP,  — sign control (always show, never show)
//   SS
//   BN, BZ  — input blank interpretation
//   $       — non-advancing output (extension)
//
// Goal: when a Fortran ``WRITE`` does **not** need any of these, the
// generated code reads as plain C++ — no ``fortran::io`` mention at
// all.  See ../README.md (rule R8 and decision D5) for the policy.
//
//===----------------------------------------------------------------------===//

#ifndef FORTRAN_RT_IO_HPP
#define FORTRAN_RT_IO_HPP

#include "array_ref.hpp" // index_t + array-like views for formatted array I/O

#include <cmath>
#include <cctype>
#include <cstddef>
#include <cstdint>
#include <cstring>      // memcpy for unformatted byte pack/unpack
#include <algorithm>
#include <cstdlib>
#include <format>
#include <fstream>
#include <iostream>
#include <map>
#include <memory>
#include <optional>
#include <string>
#include <string_view>
#include <type_traits>  // is_arithmetic_v / enable_if_t for byte helpers
#include <vector>
#include <vector>

namespace fortran::io {

// ---------------------------------------------------------------------------
// Connected file units.
//
// Fortran file units are global per-image state; per decision D2.b the
// converter threads a ``Units`` table through the call graph as ordinary
// caller-owned state (no globals), so independent program instances and
// threads stay isolated.  Preconnected units map to the standard streams
// (5 = stdin, 6 = stdout, 0 = stderr); OPEN'd units are backed by an
// ``std::fstream``.
// ---------------------------------------------------------------------------
// Stream buffer that translates Fortran list-directed separators in the
// source byte stream so an iostream's ``>>`` operator can drive
// Fortran-style reads.  In Fortran list-directed input, a comma ends one
// item and starts the next (``5,26,2010`` reads as three integers); C++
// ``>>`` would otherwise stop at the first comma and leave the next item
// unread.  Slashes ('/') and tabs also separate items; newlines and
// blanks already separate items in C++ ``>>``.
//
// Wraps a source streambuf and on every character read forwards the
// translated byte ('\\t', '/', ',' -> ' ').  Writes are not translated:
// this buffer only services reads.
class FortranListDirectedBuf : public std::streambuf {
public:
  explicit FortranListDirectedBuf(std::streambuf *src) noexcept : src_(src) {}

protected:
  int_type underflow() override {
    int_type c{src_->sbumpc()};
    if (c == traits_type::eof()) {
      return c;
    }
    ch_ = static_cast<char>(c);
    if (ch_ == ',' || ch_ == '\t') {
      // Comma and tab: Fortran list-directed input treats them as
      // field separators (equivalent to whitespace).
      ch_ = ' ';
    } else if (ch_ == 'D' || ch_ == 'd') {
      // Fortran double-precision exponent: ``2.71319D+02`` for 271.319.
      // ``std::istream::operator>>`` only understands ``E``/``e``, so the
      // ``D`` is translated on the wire so reads of D-format real fields
      // (mcsat coefficient tables, ig_rz indices, etc.) succeed.
      // Translating ``D``/``d`` -> ``E``/``e`` everywhere on input is
      // benign for non-numeric data: a CHARACTER ``READ(unit, '(A)')``
      // goes through ``getline`` which does not consult the filter.
      ch_ = (ch_ == 'D') ? 'E' : 'e';
    }
    setg(&ch_, &ch_, &ch_ + 1);
    return traits_type::to_int_type(ch_);
  }

private:
  std::streambuf *src_;
  char ch_{};
};

// File-backed iostream whose reads go through ``FortranListDirectedBuf``.
// Owns the underlying fstream so a single unique_ptr in ``Units::files_``
// keeps both alive together.  Writes go straight to ``source_->rdbuf()``
// via ``out()`` below.
class FortranFile : public std::iostream {
public:
  explicit FortranFile(std::unique_ptr<std::fstream> source)
      : std::iostream(&filter_), source_(std::move(source)),
        filter_(source_->rdbuf()) {
    if (!source_->is_open()) {
      setstate(std::ios::failbit);
    }
  }

  bool is_open() const noexcept { return source_->is_open(); }

  // Writes bypass the list-directed translator: output formatting is
  // generated by the caller and shouldn't have separators rewritten.
  std::ostream &out() noexcept { return *source_; }

  // Raw input stream (no list-directed separator translation).  Used by
  // direct-access ``read_record``, which needs exact byte offsets — the
  // filter buffer's character substitution would skew positions.
  std::istream &raw_in() noexcept { return *source_; }

  // ACCESS='DIRECT': mark this file record-based with ``recl``-byte
  // records.  ``recl()`` returns 0 for ordinary sequential files.
  void set_direct_access(int recl) noexcept { recl_ = recl; }
  int recl() const noexcept { return recl_; }

  // FORM='UNFORMATTED': mark this file as raw-byte I/O.  Records hold
  // ``recl`` bytes exactly (no trailing newline, no text encoding).
  void set_unformatted(bool u) noexcept { unformatted_ = u; }
  bool unformatted() const noexcept { return unformatted_; }

  // The filesystem path the unit was opened on -- recorded so INQUIRE
  // can report ``NAME=`` and match a file by path.  Empty for a
  // synthesized ``fort.<N>`` unit.
  void set_path(std::string p) { path_ = std::move(p); }
  const std::string &path() const noexcept { return path_; }

private:
  std::unique_ptr<std::fstream> source_;
  FortranListDirectedBuf filter_;
  int recl_{0};
  bool unformatted_{false};
  std::string path_;
};

class Units {
public:
  Units() { register_flush_at_exit(); }

  // On normal scope exit the owned fstreams flush via their own
  // destructors; we only need to drop this instance from the global
  // at-exit registry so the STOP handler never dereferences a freed
  // ``Units`` (a non-std::exit return path destroys the table here).
  ~Units() {
    auto &reg = flush_registry();
    reg.erase(std::remove(reg.begin(), reg.end(), this), reg.end());
  }

  // Non-copyable, non-movable: the at-exit registry holds a raw ``this``
  // pointer, so the object must keep a stable address for its lifetime.
  Units(const Units &) = delete;
  Units &operator=(const Units &) = delete;
  Units(Units &&) = delete;
  Units &operator=(Units &&) = delete;

  // Fortran STOP flushes all connected units before terminating, but the
  // lowered ``std::exit`` skips local destructors so the buffered output
  // of file-backed units would be lost.  An atexit handler that flushes
  // every still-open file in this instance closes that gap.
  void flush_all() noexcept {
    for (auto &kv : files_) {
      if (kv.second) {
        kv.second->out().flush();
      }
    }
  }

  void open(int unit, std::string_view file,
            std::string_view status = "unknown",
            std::string_view access = "sequential", int recl = 0,
            std::string_view form = "formatted") {
    std::ios_base::openmode mode{};
    // STATUS: OLD -> read an existing file; NEW/REPLACE -> truncate;
    // otherwise read+write, creating if needed.
    if (iequals(status, "old")) {
      mode = std::ios::in;
    } else if (iequals(status, "new") || iequals(status, "replace")) {
      // Open for read+write so the program can REWIND a just-written file
      // and read its records back; std::ios::trunc still clears any
      // pre-existing contents.
      mode = std::ios::in | std::ios::out | std::ios::trunc;
    } else {
      mode = std::ios::in | std::ios::out;
    }
    // A direct-access file is random read+write regardless of STATUS, so
    // it must always be opened for both (an OLD file stays untruncated; a
    // NEW/REPLACE one is truncated first).
    if (iequals(access, "direct")) {
      mode |= std::ios::in | std::ios::out;
    }
    bool unformatted{iequals(form, "unformatted")};
    if (unformatted) {
      mode |= std::ios::binary;
    }
    // Fortran CHARACTER variables are blank-padded to their declared length;
    // OPEN(FILE=...) trims trailing blanks before resolving the path.
    std::string path{trim_trailing_blanks(file)};
    auto fs{std::make_unique<std::fstream>(path, mode)};
    if (!fs->is_open() && (mode & std::ios::in) && !(mode & std::ios::out)) {
      // Fall back to creating the file for read/write.
      auto fallback = std::ios::in | std::ios::out | std::ios::trunc;
      if (unformatted) {
        fallback |= std::ios::binary;
      }
      fs = std::make_unique<std::fstream>(path, fallback);
    }
    auto file_obj{std::make_unique<FortranFile>(std::move(fs))};
    if (iequals(access, "direct")) {
      file_obj->set_direct_access(recl);
    }
    file_obj->set_unformatted(unformatted);
    file_obj->set_path(path);
    files_[unit] = std::move(file_obj);
  }

  // ACCESS='DIRECT' record read.  Returns the bytes of record ``rec``
  // (1-based) as a string with any trailing newline trimmed; the caller
  // parses fixed-width fields from it.  Fortran's RECL for a FORMATTED
  // direct file counts the record's textual width *including* its
  // terminating newline (here RECL=39 = 38 content chars + '\n'), so the
  // on-disk stride is exactly ``recl`` bytes.
  std::string read_record(int unit, int rec) {
    auto &file = ensure(unit);
    int recl{file.recl()};
    if (recl <= 0) {
      // Unit not opened ACCESS='DIRECT'; degrade to a line read.
      std::string line;
      std::getline(file.raw_in(), line);
      return line;
    }
    std::streamoff stride{static_cast<std::streamoff>(recl)};
    file.raw_in().clear();
    file.raw_in().seekg(stride * (rec - 1));
    std::string buf(static_cast<std::size_t>(recl), ' ');
    file.raw_in().read(buf.data(), recl);
    auto n = file.raw_in().gcount();
    buf.resize(static_cast<std::size_t>(n));
    while (!buf.empty() && (buf.back() == '\n' || buf.back() == '\r')) {
      buf.pop_back();
    }
    return buf;
  }

  // ACCESS='DIRECT' record write — the inverse of read_record.  The
  // formatted ``content`` is blank-padded (Fortran-style) or truncated to
  // recl-1 chars, terminated with a newline (recl bytes total), and placed
  // at record ``rec``'s slot so it round-trips with read_record's
  // recl-byte stride.
  void write_record(int unit, int rec, std::string content) {
    auto &file = ensure(unit);
    int recl{file.recl()};
    auto &os = file.out();
    if (recl <= 0) {
      // Not a direct-access unit; degrade to a plain line write.
      os << content << '\n';
      return;
    }
    content.resize(static_cast<std::size_t>(recl - 1), ' ');
    content.push_back('\n');
    os.seekp(static_cast<std::streamoff>(recl) * (rec - 1));
    os.write(content.data(), recl);
    os.flush();
  }

  // FORM='UNFORMATTED', ACCESS='DIRECT' record read.  Returns the raw
  // ``recl`` bytes of record ``rec`` -- no newline framing, no character
  // encoding -- so the caller can deserialize typed items (scalars,
  // arrays, character variables) byte-for-byte the way Fortran wrote
  // them.  The on-disk stride is exactly ``recl`` bytes.
  std::vector<std::byte> read_record_raw(int unit, int rec) {
    auto &file = ensure(unit);
    int recl{file.recl()};
    if (recl <= 0) {
      return {};
    }
    std::streamoff stride{static_cast<std::streamoff>(recl)};
    file.raw_in().clear();
    file.raw_in().seekg(stride * (rec - 1));
    std::vector<std::byte> buf(static_cast<std::size_t>(recl));
    file.raw_in().read(reinterpret_cast<char *>(buf.data()), recl);
    auto n = file.raw_in().gcount();
    buf.resize(static_cast<std::size_t>(n));
    return buf;
  }

  // FORM='UNFORMATTED', ACCESS='DIRECT' record write -- inverse of
  // read_record_raw.  ``content`` is zero-padded (or truncated) to
  // exactly ``recl`` bytes, placed at record ``rec``'s slot.
  void write_record_raw(int unit, int rec,
                        const std::vector<std::byte> &content) {
    auto &file = ensure(unit);
    int recl{file.recl()};
    auto &os = file.out();
    if (recl <= 0) {
      os.write(reinterpret_cast<const char *>(content.data()),
               static_cast<std::streamsize>(content.size()));
      os.flush();
      return;
    }
    std::vector<std::byte> rec_buf(static_cast<std::size_t>(recl),
                                   std::byte{0});
    std::size_t n = std::min(content.size(), rec_buf.size());
    std::memcpy(rec_buf.data(), content.data(), n);
    os.seekp(static_cast<std::streamoff>(recl) * (rec - 1));
    os.write(reinterpret_cast<const char *>(rec_buf.data()), recl);
    os.flush();
  }

  void close(int unit) { files_.erase(unit); }

  // INQUIRE results.  Each member maps to one Fortran specifier
  // (``EXIST``, ``OPENED``, ``IOSTAT``, ``NUMBER``, ``NAME``, ``ACCESS``,
  // ``FORM``, ``RECL``); unset fields keep their defaults.  The lowering
  // pass writes only the ones the source actually asked for.
  struct InquireResult {
    bool exist{false};
    bool opened{false};
    int iostat{0};
    int number{-1};
    int recl{0};
    std::string name;
    std::string access;
    std::string form;
  };

  // ``INQUIRE(FILE=path, ...)``: properties of a named file.  EXIST is
  // resolved on the filesystem; OPENED tells whether *any* of our open
  // units points at this path (matching Fortran semantics, modulo
  // case-/symlink-canonicalization).
  InquireResult inquire_by_file(std::string_view file) {
    InquireResult r;
    std::string path{trim_trailing_blanks(file)};
    std::ifstream probe(path);
    r.exist = probe.is_open();
    r.name = path;
    for (auto &kv : files_) {
      // Two file paths point at the same file only if the OS sees them
      // that way; we do a plain string compare here -- enough for the
      // SPICE usage which just checks whether *this* path is connected.
      if (kv.second && kv.second->path() == path) {
        r.opened = true;
        r.number = kv.first;
        r.access = kv.second->recl() > 0 ? "DIRECT" : "SEQUENTIAL";
        r.form = kv.second->unformatted() ? "UNFORMATTED" : "FORMATTED";
        r.recl = kv.second->recl();
        break;
      }
    }
    return r;
  }

  // ``INQUIRE(UNIT=u, ...)``: properties of a unit.  ``OPENED`` is true
  // iff the unit has a FortranFile in our table; ``NAME`` and the
  // access/form/recl fields come from the OPEN call's recorded
  // parameters.  An ordinary sequential text file reports
  // ACCESS=SEQUENTIAL FORM=FORMATTED RECL=0.
  InquireResult inquire_by_unit(int unit) {
    InquireResult r;
    r.number = unit;
    auto it = files_.find(unit);
    if (it == files_.end() || !it->second) {
      return r;
    }
    r.opened = true;
    r.exist = true;
    r.name = it->second->path();
    r.access = it->second->recl() > 0 ? "DIRECT" : "SEQUENTIAL";
    r.form = it->second->unformatted() ? "UNFORMATTED" : "FORMATTED";
    r.recl = it->second->recl();
    return r;
  }

  // ``BACKSPACE(u)``: undo the last sequential read/write so the next
  // operation re-runs on that record.  For a formatted sequential file
  // this is "seek back past the previous newline"; for a direct file it
  // decrements the record cursor.  Errors on a non-positionable stream
  // (stdin/stdout, internal-file, no record yet read) are reported as
  // IOSTAT == 0 (best-effort) -- matches Fortran's permissive defaults.
  void backspace(int unit) {
    auto &file = ensure(unit);
    auto &is = file.raw_in();
    if (!is.good()) {
      is.clear();
    }
    auto pos = is.tellg();
    if (pos <= std::streampos(0)) {
      return;
    }
    if (file.recl() > 0) {
      is.seekg(pos - std::streamoff(file.recl()));
      return;
    }
    // Sequential formatted: walk back past the previous newline.
    std::streamoff off{static_cast<std::streamoff>(pos) - 1};
    while (off > 0) {
      is.seekg(off - 1);
      char c{};
      if (!is.get(c)) {
        break;
      }
      if (c == '\n') {
        return;
      }
      --off;
    }
    is.seekg(0);
  }

  // ``REWIND(u)``: position the unit at its first record (i.e. seek to
  // byte 0).  Clears any failbit so the next read starts fresh.
  void rewind(int unit) {
    auto &file = ensure(unit);
    file.raw_in().clear();
    file.raw_in().seekg(0);
    file.out().clear();
    file.out().seekp(0);
  }

  std::ostream &out(int unit) {
    if (unit == 6) {
      return std::cout;
    }
    if (unit == 0) {
      return std::cerr;
    }
    return ensure(unit).out();
  }

  std::istream &in(int unit) {
    if (unit == 5) {
      return std::cin;
    }
    return ensure(unit);
  }

private:
  // Return the FortranFile for ``unit``, opening ``fort.<unit>`` lazily
  // the first time the unit is touched if it wasn't explicitly OPENed.
  // Matches the flang / gfortran runtime convention; without this fallback
  // a WRITE to an unattached unit would silently go to ``stdout`` and a
  // READ would silently fall through to ``std::cin``.
  FortranFile &ensure(int unit) {
    auto it{files_.find(unit)};
    if (it != files_.end()) {
      return *it->second;
    }
    auto fs{std::make_unique<std::fstream>(
        "fort." + std::to_string(unit), std::ios::in | std::ios::out)};
    if (!fs->is_open()) {
      fs = std::make_unique<std::fstream>(
          "fort." + std::to_string(unit),
          std::ios::in | std::ios::out | std::ios::trunc);
    }
    auto &slot{files_[unit]};
    slot = std::make_unique<FortranFile>(std::move(fs));
    return *slot;
  }

  // Hook a one-shot atexit that flushes this Units instance's files
  // when ``std::exit`` is called past the main_program body.  We register
  // a global tracker (a weak pointer set) so multiple Units instances
  // are all visited; in practice there is only one — the main's local.
  void register_flush_at_exit() {
    static auto &registry = flush_registry();
    static const bool installed = [] {
      std::atexit([] {
        for (Units *u : flush_registry()) {
          if (u) u->flush_all();
        }
      });
      return true;
    }();
    (void)installed;
    registry.push_back(this);
  }

  static std::vector<Units *> &flush_registry() {
    static std::vector<Units *> v;
    return v;
  }

  static std::string_view trim_trailing_blanks(std::string_view s) {
    std::size_t n{s.size()};
    while (n > 0 && (s[n - 1] == ' ' || s[n - 1] == '\t')) {
      --n;
    }
    return s.substr(0, n);
  }

  static bool iequals(std::string_view a, std::string_view b) {
    if (a.size() != b.size()) {
      return false;
    }
    for (std::size_t i = 0; i < a.size(); ++i) {
      if (std::tolower(static_cast<unsigned char>(a[i])) !=
          std::tolower(static_cast<unsigned char>(b[i]))) {
        return false;
      }
    }
    return true;
  }

  std::map<int, std::unique_ptr<FortranFile>> files_;
};

// ---------------------------------------------------------------------------
// Byte pack / unpack for FORM='UNFORMATTED' direct-access I/O.
//
// A Fortran unformatted record is a raw byte image of the items in
// declaration order: each scalar contributes its sizeof; each array
// contributes its element-bytes column-major; each CHARACTER contributes
// its declared length (no length tag).  We mirror that with two
// overload sets:
//
//   append_bytes(buf, item)             — pack ``item`` onto ``buf``
//   take_bytes(rec, offset, item)       — unpack into ``item``, advance
//                                         and return the new offset
//
// The types we support are: arithmetic scalars (int/float/double/bool/
// char), ``Array<T,R>``, ``ArrayRef<T,R>``, and ``FortranString<N>``.
// All are detected by duck-typing so this header doesn't depend on
// ``array.hpp`` / ``string.hpp``.
// ---------------------------------------------------------------------------

// Arithmetic scalars (int8..int64, float, double, bool).
template <typename T,
          std::enable_if_t<std::is_arithmetic_v<T>, int> = 0>
inline void append_bytes(std::vector<std::byte> &buf, const T &v) {
  std::byte tmp[sizeof(T)];
  std::memcpy(tmp, &v, sizeof(T));
  buf.insert(buf.end(), tmp, tmp + sizeof(T));
}

template <typename T,
          std::enable_if_t<std::is_arithmetic_v<T>, int> = 0>
inline std::size_t take_bytes(const std::vector<std::byte> &rec,
                              std::size_t off, T &v) {
  if (off + sizeof(T) > rec.size()) {
    v = T{};
    return rec.size();
  }
  std::memcpy(&v, rec.data() + off, sizeof(T));
  return off + sizeof(T);
}

// Anything exposing both a callable ``data()`` and a callable ``size()``
// over a trivially-copyable element type — covers ``Array<T,R>`` and
// ``ArrayRef<T,R>`` (and any future contiguous view).  ``FortranString``
// is intentionally excluded (it carries its length as a static
// ``length`` constant, not a ``size()`` method) so it picks the
// dedicated CHARACTER overload below.
template <typename C>
using _ab_elem_t = std::remove_reference_t<
    decltype(*std::declval<C &>().data())>;

template <typename C>
using _ab_size_t = decltype(std::declval<const C &>().size());

template <
    typename C,
    std::enable_if_t<
        std::is_arithmetic_v<std::remove_const_t<_ab_elem_t<C>>> &&
            std::is_integral_v<_ab_size_t<C>>,
        int> = 0>
inline void append_bytes(std::vector<std::byte> &buf, const C &c) {
  using E = std::remove_const_t<_ab_elem_t<C>>;
  const std::size_t n_bytes = static_cast<std::size_t>(c.size()) * sizeof(E);
  const auto *p = reinterpret_cast<const std::byte *>(c.data());
  buf.insert(buf.end(), p, p + n_bytes);
}

template <
    typename C,
    std::enable_if_t<
        std::is_arithmetic_v<std::remove_const_t<_ab_elem_t<C>>> &&
            std::is_integral_v<_ab_size_t<C>>,
        int> = 0>
inline std::size_t take_bytes(const std::vector<std::byte> &rec,
                              std::size_t off, C &c) {
  using E = std::remove_const_t<_ab_elem_t<C>>;
  const std::size_t n_bytes = static_cast<std::size_t>(c.size()) * sizeof(E);
  const std::size_t avail = off + n_bytes > rec.size()
                                ? rec.size() - std::min(off, rec.size())
                                : n_bytes;
  if (avail > 0) {
    std::memcpy(c.data(), rec.data() + off, avail);
  }
  return off + n_bytes;
}

// ``std::string_view`` (covers Fortran CHARACTER literals).
inline void append_bytes(std::vector<std::byte> &buf, std::string_view s) {
  const auto *p = reinterpret_cast<const std::byte *>(s.data());
  buf.insert(buf.end(), p, p + s.size());
}

// ``EquivArray<T, N, Off>`` (and any byte-buffer view exposing
// ``byte_data()`` + ``byte_size()``).  The bytes already live in the
// shared equivalence buffer, so this just memcpys them out / in.
template <typename E, typename = std::enable_if_t<
                          std::is_same_v<
                              decltype(std::declval<const E &>().byte_data()),
                              const std::byte *> ||
                          std::is_same_v<
                              decltype(std::declval<const E &>().byte_data()),
                              std::byte *>>>
inline void append_bytes(std::vector<std::byte> &buf, const E &e) {
  const auto *p = e.byte_data();
  buf.insert(buf.end(), p, p + e.byte_size());
}

template <typename E, typename = std::enable_if_t<
                          std::is_same_v<
                              decltype(std::declval<E &>().byte_data()),
                              std::byte *>>>
inline std::size_t take_bytes(const std::vector<std::byte> &rec,
                              std::size_t off, E &e) {
  const std::size_t n = e.byte_size();
  const std::size_t avail =
      off + n > rec.size() ? rec.size() - std::min(off, rec.size()) : n;
  if (avail > 0) {
    std::memcpy(e.byte_data(), rec.data() + off, avail);
  }
  return off + n;
}

// CHARACTER variables (``FortranString<N>``).  Matched by a static
// ``length`` constant + a ``char *`` data; explicitly excludes types
// that also expose ``byte_data()`` (``EquivArray<T,N,Off>``, which has
// both ``length`` and ``byte_data``) so dispatch is unambiguous.
template <typename S, std::size_t = S::length,
          typename = std::enable_if_t<
              std::is_same_v<decltype(std::declval<S &>().data()), char *>>>
inline void append_bytes(std::vector<std::byte> &buf, const S &s) {
  const auto *p = reinterpret_cast<const std::byte *>(s.data());
  buf.insert(buf.end(), p, p + S::length);
}

template <typename S, std::size_t = S::length,
          typename = std::enable_if_t<
              std::is_same_v<decltype(std::declval<S &>().data()), char *>>>
inline std::size_t take_bytes(const std::vector<std::byte> &rec,
                              std::size_t off, S &s) {
  const std::size_t n = S::length;
  const std::size_t avail =
      off + n > rec.size() ? rec.size() - std::min(off, rec.size()) : n;
  if (avail > 0) {
    std::memcpy(s.data(), rec.data() + off, avail);
  }
  // Fortran pads any unfilled tail with blanks on a CHARACTER read.
  for (std::size_t i = avail; i < n; ++i) {
    s.data()[i] = ' ';
  }
  return off + n;
}

// ---------------------------------------------------------------------------
// Fixed-width field parsing for formatted direct-access READ.
//
// A formatted direct read fetches a whole record (see Units::read_record)
// then slices fixed-width fields out of it per the FORMAT spec.  I-format
// ints are right-justified, blank-padded (trailing blanks read as zeros);
// F-format reals may carry sign and decimal, with an implicit decimal
// point ``d`` places from the right when no '.' is present.  Each helper
// takes the record plus a 0-based start offset and width.
// ---------------------------------------------------------------------------

inline std::int64_t read_field_int(std::string_view rec, std::size_t pos,
                                   std::size_t width) {
  if (pos >= rec.size()) {
    return 0;
  }
  std::size_t end{std::min(pos + width, rec.size())};
  std::int64_t v{0};
  int sign{1};
  std::size_t i{pos};
  while (i < end && rec[i] == ' ') {
    ++i;
  }
  if (i < end && (rec[i] == '+' || rec[i] == '-')) {
    if (rec[i] == '-') {
      sign = -1;
    }
    ++i;
  }
  for (; i < end; ++i) {
    char c{rec[i]};
    if (c >= '0' && c <= '9') {
      v = v * 10 + (c - '0');
    } else if (c == ' ') {
      // Trailing blanks in an I field read as zeros (BLANK='ZERO').
      v *= 10;
    } else {
      break;
    }
  }
  return sign * v;
}

inline double read_field_real(std::string_view rec, std::size_t pos,
                              std::size_t width, int decimals = 0) {
  if (pos >= rec.size()) {
    return 0.0;
  }
  std::size_t end{std::min(pos + width, rec.size())};
  std::string buf(rec.substr(pos, end - pos));
  std::size_t a{0};
  while (a < buf.size() && buf[a] == ' ') {
    ++a;
  }
  std::size_t b{buf.size()};
  while (b > a && buf[b - 1] == ' ') {
    --b;
  }
  if (a == b) {
    return 0.0;
  }
  std::string text(buf.substr(a, b - a));
  // Fortran double-precision exponent: ``2.71319D+02`` for 271.319.
  // ``std::stod`` only understands ``E``/``e``, so translate before parse.
  for (char &c : text) {
    if (c == 'D') c = 'E';
    else if (c == 'd') c = 'e';
  }
  bool has_dot{text.find('.') != std::string::npos};
  try {
    double v{std::stod(text)};
    if (!has_dot && decimals > 0) {
      double scale{1.0};
      for (int i = 0; i < decimals; ++i) {
        scale *= 10.0;
      }
      v /= scale;
    }
    return v;
  } catch (...) {
    return 0.0;
  }
}

// ---------------------------------------------------------------------------
// G edit descriptor — "general" numeric format.
//
// Fortran's ``Gw.dEe``:
//   * If the magnitude of the value fits in a "reasonable" range for
//     ``d`` significant digits, format like ``Fw.d`` with trailing
//     blanks for the exponent field.
//   * Otherwise, format like ``Ew.dEe``.
// The exact pivot is defined by the standard (F2018 §13.7.5.3.3):
//   use F-format when 0.1 <= |x| < 10^d, else E-format.
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// E edit descriptor — scientific notation, Fortran style.
//
// Fortran's ``Ew.d`` normalizes the mantissa to the range [0.1, 1.0)
// and prints a leading "0.", e.g. ``E12.4`` of 3.14159 is
// "  0.3142E+01" — distinct from C++'s ``{:e}`` which normalizes to
// [1, 10) ("3.1416e+00").  We therefore hand-format to match Fortran.
//
//   w = total field width, d = digits after the decimal point,
//   e = exponent digit count (default 2).
// ---------------------------------------------------------------------------

inline std::string fmt_E(double value, int w, int d,
                         std::optional<int> e = std::nullopt) {
  const int edigits = e.value_or(2);
  const bool neg = std::signbit(value);
  double a = std::abs(value);

  int exp = 0;
  if (a != 0.0) {
    exp = static_cast<int>(std::floor(std::log10(a))) + 1;  // 0.x * 10^exp
    a /= std::pow(10.0, exp);
    // Guard against rounding pushing the mantissa to 1.0.
    if (a >= 1.0) {
      a /= 10.0;
      ++exp;
    }
  }
  // Mantissa with d digits after the implicit "0.".
  std::string mant = std::format("{:.{}f}", a, d);  // "0.3142"
  // Exponent field: sign + edigits digits.
  std::string exp_str = std::format("{:0{}d}", std::abs(exp), edigits);
  std::string body = (neg ? "-" : "") + mant + "E" +
                     (exp < 0 ? "-" : "+") + exp_str;
  // Right-justify into width w.
  if (static_cast<int>(body.size()) < w) {
    body.insert(body.begin(), w - body.size(), ' ');
  }
  return body;
}

inline std::string fmt_G(double value, int w, int d,
                         std::optional<int> e = std::nullopt) {
  using std::abs;
  const double a = abs(value);
  bool use_f = false;
  // 0.1 <= a < 10^d  →  F format.  Treat 0 as in-range.
  if (a == 0.0) {
    use_f = true;
  } else if (a >= 0.1 && a < std::pow(10.0, d)) {
    use_f = true;
  }
  if (use_f) {
    // F-format with the standard's blank-exponent trailing space:
    //   Gw.d -> Fw.(d-k-1) followed by (e+2) blanks, where k is the
    //   number of digits before the decimal point.  We compute k
    //   from the rounded value to match flang.
    int k;
    if (a == 0.0) {
      k = 1;
    } else {
      k = static_cast<int>(std::floor(std::log10(a))) + 1;
      if (k < 1) k = 1;
    }
    const int fdigits = d - k;
    const int blanks = (e.value_or(2)) + 2;
    std::string body = std::format("{0:{1}.{2}f}", value,
                                   w - blanks, fdigits < 0 ? 0 : fdigits);
    body.append(static_cast<std::size_t>(blanks), ' ');
    return body;
  }
  // Otherwise E-format with the same width and d digits.
  const int eDigits = e.value_or(2);
  // std::format spec: ``{:>{}.{}e}`` produces 'd.dddde[+/-]ee'.
  std::string body =
      std::format("{0:>{1}.{2}e}", value, w, d > 0 ? d - 1 : 0);
  (void)eDigits;  // std::format always uses at least 2 exponent digits.
  return body;
}

// ---------------------------------------------------------------------------
// P scale factor — multiplies the value by 10^scale before applying an
// F or E edit descriptor.  Fortran's ``kP, Fw.d`` etc.  The scale is
// part of the FORMAT processor state; we model it as an explicit
// helper called once per affected descriptor.
// ---------------------------------------------------------------------------

inline std::string fmt_F_with_scale(double value, int scale, int w, int d) {
  // Fortran F format always shows the decimal point — ``#`` is the
  // matching std::format alternate-form flag.
  return std::format("{0:#{1}.{2}f}", value * std::pow(10.0, scale), w, d);
}

inline std::string fmt_E_with_scale(double value, int scale, int w, int d,
                                    std::optional<int> e = std::nullopt) {
  // Fortran ``kP, Ew.d`` shows the mantissa with ``k`` digits before
  // the decimal and ``d`` digits after; the labeled exponent decreases
  // by ``k`` so the printed value still equals the input.
  const int edigits = e.value_or(2);
  const bool neg = std::signbit(value);
  double a = std::abs(value);

  int exp = 0;
  if (a != 0.0) {
    exp = static_cast<int>(std::floor(std::log10(a))) + 1;  // 0.x * 10^exp
    a /= std::pow(10.0, exp);
    if (a >= 1.0) {
      a /= 10.0;
      ++exp;
    }
  }
  // Shift the mantissa left by ``scale`` and reduce the exponent by
  // the same amount so the represented value is unchanged.  Zero has no
  // exponent to scale — leave it at the default ``0`` so the printed
  // form is ``0.00E+00`` rather than ``0.00E-k``.
  if (value != 0.0) {
    a *= std::pow(10.0, scale);
    exp -= scale;
  }
  // ``a`` now has ``scale`` digits before the decimal (in the typical
  // 1P case: in [1.0, 10.0)).  Format with ``d`` digits after.
  std::string mant = std::format("{:.{}f}", a, d);
  std::string exp_str = std::format("{:0{}d}", std::abs(exp), edigits);
  std::string body = (neg ? "-" : "") + mant + "E" +
                     (exp < 0 ? "-" : "+") + exp_str;
  if (static_cast<int>(body.size()) < w) {
    body.insert(body.begin(), w - body.size(), ' ');
  }
  return body;
}

// ---------------------------------------------------------------------------
// Tab controls.
//
// In Fortran a FORMAT string drives a record buffer; T<n> repositions
// the cursor.  ``pad_to`` advances ``out`` to (1-based) column ``col``
// by emitting blanks (or truncating, though that case is unusual).
// ---------------------------------------------------------------------------

/// Advance ``buf`` to 1-based column ``col`` by padding with blanks.
inline void pad_to(std::string &buf, int col) {
  const std::size_t target = col > 0 ? static_cast<std::size_t>(col - 1) : 0;
  if (buf.size() < target) {
    buf.append(target - buf.size(), ' ');
  }
}

/// Move cursor right by ``n`` columns.  Equivalent to TR<n> or to
/// the Fortran ``X`` edit descriptor when ``n`` blanks of spacing
/// are needed and a plain ``" "`` literal would be less readable.
inline std::string skip(int n) {
  return std::string(n > 0 ? static_cast<std::size_t>(n) : 0, ' ');
}

// ---------------------------------------------------------------------------
// Sign control — Fortran ``S``, ``SP`` (always print +), ``SS`` (never
// print +).  std::format only supports the SP case (via the ``+`` sign
// flag), so SS — usually the implicit default anyway — and the
// "restore default" S are handled here.
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// List-directed READ helpers.
//
// C++11's ``operator>>`` zeros the target on failure (e.g. non-numeric
// input), whereas Fortran list-directed input on a ``/`` terminator (or
// any input that ends the list early) leaves remaining items at their
// **current values**.  ``read_list_item`` saves the destination, reads
// through ``>>``, and restores the saved value if the read fails — so
// Fortran's "keep current value on /" semantics survive C++11's zeroing.
// Returns ``true`` on success so caller chains via ``&&`` to stop the
// rest of the item list once one item fails.
// ---------------------------------------------------------------------------

template <class S, class T>
inline bool read_list_item(S &stream, T &v) {
  T save = v;
  stream >> v;
  if (stream.fail()) {
    v = save;
    return false;
  }
  return true;
}

inline std::string fmt_int_force_sign(long long value, int w) {
  return std::format("{0:+{1}d}", value, w);  // SP
}
inline std::string fmt_int_no_sign(long long value, int w) {
  // SS: never show '+', and never show ' ' either; only '-' for negatives.
  return std::format("{0:{1}d}", value, w);
}

// ---------------------------------------------------------------------------
// A edit descriptor — character output.  When the item is a character
// string we right-justify (Fortran's behavior for ``Aw`` when the item
// is shorter than the field) or truncate (longer).  When the item is a
// numeric type, Fortran reinterprets its underlying bytes as characters
// — common in F77 code that stores text in INTEGER variables via DATA
// statements.
// ---------------------------------------------------------------------------

inline std::string fmt_A(std::string_view s, int w) {
  if (static_cast<int>(s.size()) >= w) {
    return std::string(s.substr(s.size() - w, w));
  }
  std::string out(w - s.size(), ' ');
  out.append(s);
  return out;
}

inline std::string fmt_A_default(std::string_view s) {
  return std::string(s);
}

template <std::size_t N>
inline std::string fmt_A(const FortranString<N> &v, int w) {
  return fmt_A(v.view(), w);
}

template <std::size_t N>
inline std::string fmt_A_default(const FortranString<N> &v) {
  return std::string(v.view());
}

template <typename T,
          std::enable_if_t<std::is_integral_v<T> || std::is_floating_point_v<T>,
                           int> = 0>
inline std::string fmt_A(const T &v, int w) {
  // Reinterpret ``v``'s bytes as a character buffer.  Fortran is
  // little-endian on x86 but stores characters in source order, so the
  // bytes of a left-aligned ASCII pack form the character record.
  // ``w`` may exceed the size of T (pad with spaces) or be smaller
  // (truncate to the leading bytes — Fortran A descriptor truncates
  // from the right).
  constexpr std::size_t bytes = sizeof(T);
  unsigned char buf[bytes];
  std::memcpy(buf, &v, bytes);
  std::string text;
  text.reserve(bytes);
  for (std::size_t i = 0; i < bytes; ++i) {
    text.push_back(static_cast<char>(buf[i]));
  }
  return fmt_A(std::string_view(text), w);
}

template <typename T,
          std::enable_if_t<std::is_integral_v<T> || std::is_floating_point_v<T>,
                           int> = 0>
inline std::string fmt_A_default(const T &v) {
  constexpr std::size_t bytes = sizeof(T);
  unsigned char buf[bytes];
  std::memcpy(buf, &v, bytes);
  std::string text;
  text.reserve(bytes);
  for (std::size_t i = 0; i < bytes; ++i) {
    text.push_back(static_cast<char>(buf[i]));
  }
  return text;
}

// ---------------------------------------------------------------------------
// Runtime FORMAT interpreter.
//
// Almost every FORMAT is constant and is lowered at translation time to
// inline ``std::format`` / ``fmt_X`` calls.  A FORMAT that is *built at
// run time* (e.g. SPICE's ``FMT='(F@W.@F)'`` with the width/decimals
// filled in by REPMI) cannot be resolved then, so generated code routes
// it here: ``format_record(fmt, items...)`` parses the format string at
// run time and applies it to a list of type-erased items.  The interpreter
// mirrors converter/format.py so its layout matches the compile-time path.
// ---------------------------------------------------------------------------

// One output item, type-erased so a single interpreter can format a mixed
// list (an integer width, a real value, a character label, ...).
struct FmtArg {
  enum class Kind { Int, Real, Text, Logical };
  Kind kind{Kind::Text};
  long long i{0};
  double r{0.0};
  bool b{false};
  std::string s;

  double as_real() const {
    switch (kind) {
    case Kind::Int: return static_cast<double>(i);
    case Kind::Real: return r;
    case Kind::Logical: return b ? 1.0 : 0.0;
    default: return 0.0;
    }
  }
  long long as_int() const {
    switch (kind) {
    case Kind::Int: return i;
    case Kind::Real: return static_cast<long long>(r);
    case Kind::Logical: return b ? 1 : 0;
    default: return 0;
    }
  }
};

template <class T> inline FmtArg make_fmt_arg(const T &v) {
  FmtArg a;
  if constexpr (std::is_same_v<std::remove_cv_t<T>, bool>) {
    a.kind = FmtArg::Kind::Logical;
    a.b = v;
  } else if constexpr (std::is_integral_v<T>) {
    a.kind = FmtArg::Kind::Int;
    a.i = static_cast<long long>(v);
  } else if constexpr (std::is_floating_point_v<T>) {
    a.kind = FmtArg::Kind::Real;
    a.r = static_cast<double>(v);
  } else if constexpr (std::is_convertible_v<T, std::string_view>) {
    a.kind = FmtArg::Kind::Text;
    a.s = std::string(std::string_view(v));
  } else {
    // Last resort: anything else streamable becomes its numeric value.
    a.kind = FmtArg::Kind::Real;
    a.r = static_cast<double>(v);
  }
  return a;
}

namespace detail {

// Split a format body on top-level commas, mirroring format.py's
// _split_top_level: quotes, parenthesized groups, Hollerith (nH), and
// ``/`` runs are kept intact.  Hollerith and quoted text become tokens
// beginning with a single quote so apply-token routes them as literals.
inline std::vector<std::string> fmt_split(std::string_view body) {
  std::vector<std::string> parts;
  std::string buf;
  int depth = 0;
  std::size_t i = 0, n = body.size();
  auto flush_pending = [&] {
    std::size_t a = 0, b = buf.size();
    while (a < b && std::isspace((unsigned char)buf[a])) ++a;
    while (b > a && std::isspace((unsigned char)buf[b - 1])) --b;
    if (b > a) parts.emplace_back(buf.substr(a, b - a));
    buf.clear();
  };
  while (i < n) {
    char c = body[i];
    if (std::isdigit((unsigned char)c) && depth == 0) {
      std::size_t j = i;
      while (j < n && std::isdigit((unsigned char)body[j])) ++j;
      if (j < n && (body[j] == 'H' || body[j] == 'h')) {
        int count = std::stoi(std::string(body.substr(i, j - i)));
        std::size_t start = j + 1;
        std::size_t end = std::min(start + count, n);
        flush_pending();
        std::string lit = "'";
        for (std::size_t k = start; k < end; ++k) {
          if (body[k] == '\'') lit += "''";
          else lit += body[k];
        }
        lit += "'";
        parts.push_back(lit);
        i = end;
        continue;
      }
    }
    if (c == '\'' || c == '"') {
      char q = c;
      buf += c;
      ++i;
      while (i < n) {
        buf += body[i];
        if (body[i] == q) {
          if (i + 1 < n && body[i + 1] == q) { buf += body[i + 1]; i += 2; continue; }
          ++i;
          break;
        }
        ++i;
      }
      continue;
    }
    if (c == '(') ++depth;
    else if (c == ')') --depth;
    if (c == ',' && depth == 0) { flush_pending(); ++i; continue; }
    if (c == '/' && depth == 0) {
      flush_pending();
      std::string run;
      while (i < n && body[i] == '/') { run += '/'; ++i; }
      parts.push_back(run);
      continue;
    }
    buf += c;
    ++i;
  }
  flush_pending();
  return parts;
}

struct FmtCursor {
  const std::vector<FmtArg> &args;
  std::size_t ai{0};
  int scale{0};
  std::string out;
};

inline void fmt_emit_data(FmtCursor &cur, char letter, int w, bool has_w,
                          int d, bool has_d, std::optional<int> e) {
  const FmtArg *arg = cur.ai < cur.args.size() ? &cur.args[cur.ai] : nullptr;
  if (arg) ++cur.ai;
  switch (letter) {
  case 'I': {
    long long v = arg ? arg->as_int() : 0;
    cur.out += has_w ? std::format("{0:{1}d}", v, w) : std::format("{}", v);
    break;
  }
  case 'F': {
    double v = arg ? arg->as_real() : 0.0;
    if (cur.scale)
      cur.out += fmt_F_with_scale(v, cur.scale, w, has_d ? d : 0);
    else if (has_w && has_d)
      cur.out += std::format("{0:#{1}.{2}f}", v, w, d);
    else
      cur.out += std::format("{}", v);
    break;
  }
  case 'E':
  case 'D': {
    double v = arg ? arg->as_real() : 0.0;
    int ww = has_w ? w : 15, dd = has_d ? d : 6;
    if (cur.scale) cur.out += fmt_E_with_scale(v, cur.scale, ww, dd);
    else cur.out += fmt_E(v, ww, dd, e);
    break;
  }
  case 'G': {
    double v = arg ? arg->as_real() : 0.0;
    cur.out += fmt_G(v, has_w ? w : 15, has_d ? d : 6, e);
    break;
  }
  case 'A': {
    std::string s = arg ? (arg->kind == FmtArg::Kind::Text
                               ? arg->s
                               : std::format("{}", arg->as_real()))
                        : std::string{};
    cur.out += has_w ? std::format("{0:>{1}}", s, w) : s;
    break;
  }
  case 'L': {
    bool v = arg && arg->kind == FmtArg::Kind::Logical
                 ? arg->b
                 : (arg ? arg->as_int() != 0 : false);
    cur.out += std::format("{0:>{1}}", v ? "T" : "F", has_w ? w : 1);
    break;
  }
  default:
    break;
  }
}

inline void fmt_apply_body(std::string_view body, FmtCursor &cur);

inline void fmt_apply_token(std::string_view tok, FmtCursor &cur) {
  std::size_t a = 0, b = tok.size();
  while (a < b && std::isspace((unsigned char)tok[a])) ++a;
  while (b > a && std::isspace((unsigned char)tok[b - 1])) --b;
  tok = tok.substr(a, b - a);
  if (tok.empty()) return;

  // Repeated / nested group: ``n(...)`` or ``(...)``.
  {
    std::size_t p = 0;
    int rep = 0; bool has_rep = false;
    while (p < tok.size() && std::isdigit((unsigned char)tok[p])) {
      rep = rep * 10 + (tok[p] - '0'); has_rep = true; ++p;
    }
    if (p < tok.size() && tok[p] == '(' && tok.back() == ')') {
      std::string_view inner = tok.substr(p + 1, tok.size() - p - 2);
      int times = has_rep ? rep : 1;
      for (int k = 0; k < times; ++k) fmt_apply_body(inner, cur);
      return;
    }
  }
  // Quoted literal.
  if (tok.front() == '\'' || tok.front() == '"') {
    char q = tok.front();
    std::string inner;
    for (std::size_t k = 1; k < tok.size(); ++k) {
      if (tok[k] == q) {
        if (k + 1 < tok.size() && tok[k + 1] == q) { inner += q; ++k; continue; }
        break;
      }
      inner += tok[k];
    }
    cur.out += inner;
    return;
  }
  // Slash run -> one newline each.
  if (tok.front() == '/') {
    for (char ch : tok) if (ch == '/') cur.out += '\n';
    return;
  }
  // ``kP`` scale factor, possibly glued to a descriptor (``1PE12.2``).
  {
    std::size_t p = 0;
    bool neg = false;
    if (tok[p] == '+' || tok[p] == '-') { neg = tok[p] == '-'; ++p; }
    std::size_t ds = p;
    int val = 0;
    while (p < tok.size() && std::isdigit((unsigned char)tok[p])) {
      val = val * 10 + (tok[p] - '0'); ++p;
    }
    if (p > ds && p < tok.size() && (tok[p] == 'P' || tok[p] == 'p')) {
      cur.scale = neg ? -val : val;
      std::string_view rest = tok.substr(p + 1);
      if (!rest.empty()) fmt_apply_token(rest, cur);
      return;
    }
  }
  // ``$`` non-advancing marker -- no field, no newline.
  if (tok == "$") return;
  // Descriptor: [repeat] letter [width] [.dec] [E exp].
  std::size_t p = 0;
  int repeat = 0; bool has_rep = false;
  while (p < tok.size() && std::isdigit((unsigned char)tok[p])) {
    repeat = repeat * 10 + (tok[p] - '0'); has_rep = true; ++p;
  }
  if (p >= tok.size() || !std::isalpha((unsigned char)tok[p])) return;
  char letter = std::toupper((unsigned char)tok[p]);
  ++p;
  int width = 0; bool has_w = false;
  while (p < tok.size() && std::isdigit((unsigned char)tok[p])) {
    width = width * 10 + (tok[p] - '0'); has_w = true; ++p;
  }
  int dec = 0; bool has_d = false;
  if (p < tok.size() && tok[p] == '.') {
    ++p;
    while (p < tok.size() && std::isdigit((unsigned char)tok[p])) {
      dec = dec * 10 + (tok[p] - '0'); has_d = true; ++p;
    }
  }
  std::optional<int> exp;
  if (p < tok.size() && (tok[p] == 'E' || tok[p] == 'e')) {
    ++p; int ev = 0; bool has_e = false;
    while (p < tok.size() && std::isdigit((unsigned char)tok[p])) {
      ev = ev * 10 + (tok[p] - '0'); has_e = true; ++p;
    }
    if (has_e) exp = ev;
  }
  if (letter == 'X') {
    int count = has_rep ? repeat : 1;
    cur.out.append(static_cast<std::size_t>(count > 0 ? count : 0), ' ');
    return;
  }
  if (letter == 'I' || letter == 'F' || letter == 'E' || letter == 'D' ||
      letter == 'G' || letter == 'A' || letter == 'L') {
    int times = has_rep ? repeat : 1;
    for (int k = 0; k < times; ++k)
      fmt_emit_data(cur, letter, width, has_w, dec, has_d, exp);
    return;
  }
  // Unknown descriptor: skip (the constant-format path raises on these at
  // translation time; here we keep going so a partial format still runs).
}

inline void fmt_apply_body(std::string_view body, FmtCursor &cur) {
  for (auto &tok : fmt_split(body)) fmt_apply_token(tok, cur);
}

} // namespace detail

// Strip one layer of surrounding parentheses and interpret *fmt* against
// *args*, returning the formatted record text.
inline std::string vformat_record(std::string_view fmt,
                                  const std::vector<FmtArg> &args) {
  std::size_t a = 0, b = fmt.size();
  while (a < b && std::isspace((unsigned char)fmt[a])) ++a;
  while (b > a && std::isspace((unsigned char)fmt[b - 1])) --b;
  fmt = fmt.substr(a, b - a);
  if (!fmt.empty() && fmt.front() == '(' && fmt.back() == ')')
    fmt = fmt.substr(1, fmt.size() - 2);
  detail::FmtCursor cur{args};
  detail::fmt_apply_body(fmt, cur);
  return std::move(cur.out);
}

template <class... Ts>
inline std::string format_record(std::string_view fmt, const Ts &...items) {
  std::vector<FmtArg> args;
  args.reserve(sizeof...(items));
  (args.push_back(make_fmt_arg(items)), ...);
  return vformat_record(fmt, args);
}

// ---------------------------------------------------------------------------
// Formatted output of a whole array / section: one edit descriptor repeats
// over every element, e.g. ``write(u, '(9e13.4)') a(1:9)``.  Each ``fmt_X``
// gains an array overload that maps the scalar formatter over the elements
// (column-major) and concatenates the fixed-width fields.
// ---------------------------------------------------------------------------

namespace detail {
template <typename A>
concept FormatArray = requires(const A &a, index_t k) {
  a.size();
  a.linear_at(k);
};
} // namespace detail

template <detail::FormatArray A>
std::string fmt_E(const A &a, int w, int d, std::optional<int> e = std::nullopt) {
  std::string out;
  for (index_t i = 0; i < a.size(); ++i)
    out += fmt_E(static_cast<double>(a.linear_at(i)), w, d, e);
  return out;
}
template <detail::FormatArray A>
std::string fmt_G(const A &a, int w, int d, std::optional<int> e = std::nullopt) {
  std::string out;
  for (index_t i = 0; i < a.size(); ++i)
    out += fmt_G(static_cast<double>(a.linear_at(i)), w, d, e);
  return out;
}
template <detail::FormatArray A>
std::string fmt_E_with_scale(const A &a, int scale, int w, int d) {
  std::string out;
  for (index_t i = 0; i < a.size(); ++i)
    out += fmt_E_with_scale(static_cast<double>(a.linear_at(i)), scale, w, d);
  return out;
}
template <detail::FormatArray A>
std::string fmt_F_with_scale(const A &a, int scale, int w, int d) {
  std::string out;
  for (index_t i = 0; i < a.size(); ++i)
    out += fmt_F_with_scale(static_cast<double>(a.linear_at(i)), scale, w, d);
  return out;
}
template <detail::FormatArray A>
std::string fmt_int_force_sign(const A &a, int w) {
  std::string out;
  for (index_t i = 0; i < a.size(); ++i)
    out += fmt_int_force_sign(static_cast<long long>(a.linear_at(i)), w);
  return out;
}
template <detail::FormatArray A>
std::string fmt_int_no_sign(const A &a, int w) {
  std::string out;
  for (index_t i = 0; i < a.size(); ++i)
    out += fmt_int_no_sign(static_cast<long long>(a.linear_at(i)), w);
  return out;
}

} // namespace fortran::io

namespace fortran {

/// List-directed logical output character.  Fortran prints logicals as
/// ``T`` / ``F`` rather than C++'s default ``1`` / ``0``; generated
/// ``print *`` chains wrap logical items in this so the output matches.
inline char logical_text(bool b) noexcept { return b ? 'T' : 'F'; }

} // namespace fortran

#endif // FORTRAN_RT_IO_HPP
